### PR TITLE
TASK: refactor workspaces handling

### PR DESCRIPTION
**Pull request by dimaip**
When there are pending changes, I propose to block the workspace change dropdown and show the explanation in a tooltip, instead of tempting users to click and only then show the warning popup.

image

- [x] Rewrite tests
- [x] Proper notification when workspace has unpublished changes

### CODE REVIEW

**Comment by dimaip** [comment]
Merge after #483

**Comment by skurfuerst** [comment]
can you rebase plz? :)

**Comment by dimaip** [comment]
@skurfuerst just did

**Comment by skurfuerst** [comment]
<3 Thanks!

**Pull request merged**
