### PR TITLE
FEATURE: implement forceCrop option for Image editor

### PR DESCRIPTION
**Pull request by dimaip**
Resolves: #1525 

Adds an option to the Image editor to force showing the crop dialog on image upload. Could be especially useful for image editors with locked crop aspect ratio.

TODO: add documentation

```
  properties:
    teaserImage:
      ui:
        inspector:
          editorOptions:
            crop:
              aspectRatio:
                forceCrop: TRUE
```

peek 2018-04-22 21-38

### CODE REVIEW

**Comment by mstruebing** [comment]
Is this ready for review? - I mean because of the 'in progress' label

**Comment by DrillSergeant** [comment]
Perfect, your video shows exactly what we hoped for. I like it.

**Comment by dimaip** [comment]
@jonnitto https://github.com/neos/neos-development-collection/pull/2049

**Comment by DrillSergeant** [comment]
@dimaip I just tested it and it works as expected. Thank you.

**Pull request merged**
