### PR TITLE
TASK: Remove vscode settings from project repository

### PR DESCRIPTION
**Pull request by kitsunet**
If you need this, you should .gitignore the file in your
personal gitignore and put it there in your local installation.
This should never end up in the repository.

### CODE REVIEW

**Comment by mstruebing** [comment]
@skurfuerst :)

**Comment by skurfuerst** [comment]
I disagree - why not make life easier for people using vs code?

**Comment by kitsunet** [comment]
I mean, I don't feel SUPER strong about it, but if we do it with vscode, I could put my atom settings, someone else vim settings or whatever and it quickly becomes messy?

**Comment by dimaip** [comment]
I don't mind it either, if that's something globally useful and not opinionated... But German comments? Well, I'm already learning German ;)

**Comment by skurfuerst** [comment]
Hey,

If we remove this file, we'd also need to remove the file https://github.com/neos/neos-ui/blob/master/packages/jsconfig.json - as they belong together.

I'd personally would like to *re-add* it, and add documentation on how VSCode can be used in the README. Then it is transparent for others to use as well. I'd personally be fine if others do the same for Atom, IntelliJ, ...; so people have an as-friction-less-as-possible development experience.

Fine for you?

All the best,
Sebastian

**Comment by kitsunet** [comment]
Sure :) With translated comment as @dimaip mentioned ;)

**Pull request merged**
