### PR TITLE
TASK: Fix not running unit tests on CI since yarn in 8.2

### PR DESCRIPTION
**Pull request by mhsdesign**
Lets see  what the tests say ...

https://app.circleci.com/pipelines/github/neos/neos-ui/2664/workflows/361a52c1-2b11-47c6-a50b-31c5e16fdb56/jobs/12119
currently (only on 8.2)

image

### CODE REVIEW

**Comment by mhsdesign** [comment]
hääää 
image

**Comment by mhsdesign** [comment]
or is this supposed to be just blank. i mean it does sas exit code 0 - but i dont trust that :P

in 8.1 there is the normal jest output log...

**Comment by Sebobo** [comment]
Can you try making one fail and see what happens?

**Comment by mhsdesign** [comment]
lets see

**Comment by mhsdesign** [comment]
runns through even though it should fail

**Comment by mhsdesign** [comment]
Okay so `yarn workspaces foreach --parallel run test` doesnt work but a single workspace works ... `yarn workspace @neos-project/neos-ui run test`

**Comment by mhsdesign** [comment]
Okay running in parallel doesnt work on ci

**Comment by mhsdesign** [comment]
Todo: regression since 8.2 https://github.com/neos/neos-ui/issues/3258

**Pull request merged**
