### PR TITLE
BUGFIX: Fix help message styling

### PR DESCRIPTION
**Pull request by NicoleNitschke**
**What I did**
* fixed small frontend issues in help messages
*  show lists with bullet points and indents
* fix image overflowing black background

**How I did it**
* changed CSS for help messages

**How to verify it**
* add an image and a help message with a list in markdown style and see how beautiful it looks :)

### Before:
grafik

### After:
grafik

### CODE REVIEW

**Review by kitsunet — APPROVED** [review]

**Comment by kitsunet** [comment]
Great! That helps so much with readability. :)

**Comment by lorenzulrich** [comment]
Nice fix, I think you should update your commit message to respect the commit message format. I'm not sure if there's another place where you would find this, but it's still the same as here: https://discuss.neos.io/t/commit-message-style/507

So basically it could read like this:

> BUGFIX: Improve help message styling

**Review by crydotsnake — APPROVED** [review]
Thanks a lot for this improvement!

**Comment by Sebobo** [comment]
Thx for solving my issue :)

**Pull request merged**
