### PR TITLE
TASK: Add Neos Button UI component

### PR DESCRIPTION
**Pull request by dfeyer**

### CODE REVIEW

**Comment by dfeyer** [comment]
An experiment to include the "Neos" style to have a more "branded" backend a feeling to be in a production of the Neos Project, if we agree that this button can be somehow our "visual/abstract" sign

**Comment by kitsunet** [comment]
I somehow like this idea, gives the whole thing more personality.

**Comment by dfeyer** [comment]
Just a copy / paste from slack:

> but we could place the "Neos" logo somewhere
Basically I want something more soft, and feel nice to not have the logo in the backend

**Comment by daniellienert** [comment]
It definitely makes it special. I think it is a bit too much "edge" for those small buttons.

**Comment by beheist** [comment]
I'm not a huge fan. They look a bit out of place there, with the rest of the backend being very boxy.

**Comment by crazydrecksack** [comment]
I also like it but currently I am a little bit unsure. Currently it is really to visually connect the product itself with the promotion of the product and the brand. I guess the best would be to shortly ask the team on Sack or maybe create a discuss post? @dfeyer

**Comment by dfeyer** [comment]
No clue why travis fail, all failed check are outside of this change

**Comment by skurfuerst** [comment]
closing this one for now, can be implemented using extensibility

**Pull request closed without merging**
