### PR TITLE
BUGFIX: Add normalize.css to the storybook output to avoid visual ind…

### PR DESCRIPTION
**Pull request by Inkdpixels**
…ifferences between the real UI and the components #1299

### CODE REVIEW

**Comment by dimaip** [comment]
Failing test (styling)

**Comment by dimaip** [comment]
@Inkdpixels or anyone, so let's fix the tests and merge?

**Comment by Inkdpixels** [comment]
@dimaip fixed

**Comment by dimaip** [comment]
Thanks Tyll!

**Pull request merged**
