### PR TITLE
FEATURE: sort options in dimension menu

### PR DESCRIPTION
**Pull request by samuelhauser**
Sort the options in the dimension menu for better user experience with many dimension values (more then 50 languages for example).

### CODE REVIEW

**Comment by samuelhauser** [comment]
I'm not sure. Should we use the loadsh _.orderBy function?

**Comment by dimaip** [comment]
@samuelhauser yes, why not

**Comment by mstruebing** [comment]
But better `_sortBy` as it is more lightweight? :)

**Comment by samuelhauser** [comment]
Does someone know, why the tests are failing? With the local tests I don't have any errors and the output from travis does not say much.

**Pull request merged**
