### PR TITLE
TASK: Updates webpack related packages to version 4.x compatibility

### PR DESCRIPTION
**Pull request by markusguenther**
Next try ;)

Updates:
* webpack to version 4.29.1
* webpack-merge to version 4.1.5
* webpack-livereload-plugin to version 2.2.0
* json-loader to 0.5.7
* css-loader to 2.1.0
* postcss-hexrgba to 1.0.1
* postcss-import to 12.0.1
* postcss-loader to 3.0.0
* ts-loader to 5.3.3

Adds
* webpack-cli in version 3.2.3
* uglifyjs-webpack-plugin in version 2.1.1
* mini-css-extract-plugin 0.5.0

Removes
* extract-text-webpack-plugin

Resolves: #1654

### CODE REVIEW

**Comment by markusguenther** [comment]
Ok looks good at the moment only point on my list is the reset.css that is included via composes.
Hope to find the solution soonish.

**Comment by JamesAlias** [comment]
Can you elaborate on the reset.css problem?
After looking into some css files I get the feeling that it's Sass syntax in css files.

**Comment by markusguenther** [comment]
> Can you elaborate on the reset.css problem?
> After looking into some css files I get the feeling that it's Sass syntax in css files.

Yeah I know I need to push this ;)
Composes is a feature that comes with PostCss if I am not wrong.

**Comment by dimaip** [comment]
As said, it's the feature of css modules.

**Comment by JamesAlias** [comment]
> > Can you elaborate on the reset.css problem?
> > After looking into some css files I get the feeling that it's Sass syntax in css files.
> 
> Yeah I know I need to push this ;)
> Composes is a feature that comes with PostCss if I am not wrong.

Yes. But what is the _problem_? :) What does not work as intended?

**Comment by markusguenther** [comment]
```
[1/5] Resolving packages...
[2/5] Fetching packages...
warning Pattern ["@ckeditor/ckeditor5-engine@https://github.com/dimaip/ckeditor5-engine#iframe"] is trying to unpack in the same destination "/home/travis/.cache/yarn/v1/npm-@ckeditor/ckeditor5-engine-10.2.0-c0d426f95cc75d966fe11cf9f000f236213ff404" as pattern ["@ckeditor/ckeditor5-engine@^10.2.0","@ckeditor/ckeditor5-engine@^10.0.0","@ckeditor/ckeditor5-engine@^10.1.0"]. This could result in a non deterministic behavior, skipping.
error An unexpected error occurred: "https://github.com/dimaip/ckeditor5-engine: Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?".
info If you think this is a bug, please open a bug report with the information provided in "/home/travis/build/neos/neos-ui/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
make: *** [install] Error 1
The command "make setup" failed and exited with 2 during .
```

Something is now wrong with the yarn build. On the local machine it works 🤔

**Comment by markusguenther** [comment]
Ok locally there is a warning:

```
warning Pattern ["@ckeditor/ckeditor5-engine@https://github.com/dimaip/ckeditor5-engine#iframe"] is trying to unpack in the same destination "/Users/markusgunther/Library/Caches/Yarn/v1/npm-@ckeditor/ckeditor5-engine-10.2.0-c0d426f95cc75d966fe11cf9f000f236213ff404" as pattern ["@ckeditor/ckeditor5-engine@^10.2.0","@ckeditor/ckeditor5-engine@^10.2.0","@ckeditor/ckeditor5-engine@^10.2.0","@ckeditor/ckeditor5-engine@^10.2.0","@ckeditor/ckeditor5-engine@^10.2.0","@ckeditor/ckeditor5-engine@^10.2.0","@ckeditor/ckeditor5-engine@^10.2.0","@ckeditor/ckeditor5-engine@^10.2.0","@ckeditor/ckeditor5-engine@^10.2.0","@ckeditor/ckeditor5-engine@^10.2.0","@ckeditor/ckeditor5-engine@^10.2.0","@ckeditor/ckeditor5-engine@^10.0.0","@ckeditor/ckeditor5-engine@^10.1.0","@ckeditor/ckeditor5-engine@^10.2.0","@ckeditor/ckeditor5-engine@^10.2.0","@ckeditor/ckeditor5-engine@^10.1.0"]. This could result in non-deterministic behavior, skipping.
```

**Comment by markusguenther** [comment]
Sorry for the try and error driven way. But guess you can squash it later on.

**Comment by markusguenther** [comment]
Trigger travis again

**Comment by markusguenther** [comment]
Resolved conflicts and updates the dependencies

**Comment by markusguenther** [comment]
Again resolved the conflicts 🎉

**Comment by markusguenther** [comment]
I hope so. When nobody has any notes or wishes.

**Comment by markusguenther** [comment]
Updated dependencies and resolve conflicts :)

**Comment by dimaip** [comment]
Change the target branch to 2.x

**Comment by dimaip** [comment]
But there's something definitely wrong with the number of changed files. I'd create a clean PR and cherry-pick relevant commits

**Comment by markusguenther** [comment]
Closes this messed up PR in favor of https://github.com/neos/neos-ui/pull/2369

**Pull request closed without merging**
