### PR TITLE
BUGFIX: Sanitize option labels for reference and references editor

### PR DESCRIPTION
**Pull request by grebaldi**
**What I did/How I did it**

I added a preprocessing function to the `options` and `searchOptions` arrays that sanitizes the option labels, stripping HTML tags and decoding HTML entities.

For sanitation I reused the same helpers that sanitize the node labels for the document and content trees.

**How to verify it**

1. Create a content node type with a `title` property that can be edited via RTE inline. (The property name matters)

```yaml
'Vendor.Site:Content.Test':
  properties:
    title:
      type: string
      ui:
        inlineEditable: true
```

2. Create a node of that type and paste a string in there, containing some HTML entities or tags.
3. Create another node type with two properties (one for `reference` and one for `references`) that allows for references to the first node type.

```yaml
'Vendor.Site:Content.ReferenceTest':
  properties:
    reference:
      type: reference
      ui:
        label: Reference
        showInCreationDialog: true
        inspector:
          group: referenceSettings
          editorOptions:
            nodeTypes: ['Vendor.Site:Content']
    references:
      type: references
      ui:
        label: References
        showInCreationDialog: true
        inspector:
          group: referenceSettings
          editorOptions:
            nodeTypes: ['Vendor.Site:Content']
```

2. Create a node of that type and in the reference properties search for the other node.

**Before the fix** you'll see doubly encoded HTML entities:
Screenshot_2021-08-01_16-25-29

**After the fix** you should see sanitized output:
Screenshot_2021-08-01_21-46-07

fixes: #1996

### CODE REVIEW

**Comment by grebaldi** [comment]
The E2E tests will most likely work again, after https://github.com/neos/fusion-form/pull/52  has been merged and released.

After the bugfix release of Neos.Fusion.Form, the E2E tests of Neos.Neos.Ui just need to be re-run with an updated cache key prefix (as described here: https://github.com/neos/neos-ui#just-the-end-to-end-tests-fail).

**Review by kdambekalns — APPROVED** [review]
Looks good by reading.

**Review by Sebobo — CHANGES_REQUESTED** [review]
Works great for references. But the linkeditor should also get sanitized:

Bildschirmfoto 2021-08-10 um 14 34 43

**Comment by grebaldi** [comment]
whoops :sweat_smile: that makes sense, of course. I'll add that as well.

**Review by Sebobo — APPROVED** [review]
Lovely <3

**Pull request merged**
