### PR TITLE
BUGFIX: Reset border-radius for button

### PR DESCRIPTION
**Pull request by Bobeta**
Quick reset for button border-radius until normalize.css is updated #1180

### CODE REVIEW

**Comment by dimaip** [comment]
Related: https://github.com/necolas/normalize.css/issues/706

**Comment by dimaip** [comment]
Thanks!
I think our style checker complains about missing new line at the end of file.

**Comment by Bobeta** [comment]
@dimaip I made a new commit with the new line at the end of the file, is it alright now?

**Comment by dimaip** [comment]
Yep! Thanks for contributing!
If you'd feel like helping a bit more, look around, we have plenty more issues available :smile:

**Pull request merged**
