### PR TITLE
FEATURE: CKE5 integration

### PR DESCRIPTION
**Pull request by dimaip**
The default text editor is not configurable in Settings.yaml via `Neos.Neos.Ui.frontendConfiguraion.defaultInlineEditor`.
To test this editor set it to `ckeditor5`.

TODO:
- [x] sub/sup
- [x] placeholder
- [ ] removeformat
- [ ] table inline balloon UI, table styles
- [x] cleanup and documentation
- [ ] remove the CKE UI for editing the link

### CODE REVIEW

**Comment by kitsunet** [comment]
- Table styles so table is always visible
- Double click in link leads to fatal error
- New text element has no toolbar

**Comment by dimaip** [comment]
@kitsunet works on my machine (tm)

**Comment by dimaip** [comment]
@kitsunet I'll be away from internet for a week, but then I'll try to ping you to debug what happens on your machine, while it works perfectly fine on mine. Also please test the current state on master, maybe it has somehow got better?

**Comment by bwaidelich** [comment]
Did this resolve #1889 ?

**Comment by mstruebing** [comment]
I would say no as the CK5 integration is currently experimental and more or less hidden via a setting.

**Comment by kitsunet** [comment]
How do we deal with this problem (see thread)? 
https://neos-project.slack.com/archives/C0U0KEGDQ/p1530608559000131

Can we make sure that people don't need the respective ckeditor5 theme to compile their plugins?

**Comment by mstruebing** [comment]
I will look into it tomorrow!

**Comment by KPeschke** [comment]
Have also tested:
- The new link tooltip has different positions, mostly outside the node. It is currently not positioned as in your example video
- Underline and strike through missing
- The error reported by Christian with the double clicked link I had several times too. Unfortunately, it is difficult to reproduce the steps to cause this errors.
- trouble with non-block elements like span. It generates <p>-tags within the span
- missing hover and focus classes on element (blue dashed and solid outlines)
- it seems a automated spell check is active and marks the entire text in chrome

**Comment by dimaip** [comment]
Hi @KPeschke! Thanks a lot for thorough testing!

- Link tooltip will be gone, replaced by completely custom UI.
- Underline and strikethrough seem to work for me. Do you have the enabled in NodeTypes.yaml?
- Will try to debug non-block elements tonight
- Same with hover, forgot about it
- Not sure about spell check, do you know what could be triggering it? I don't think I have it personally.

**Comment by KPeschke** [comment]
Hi @dimaip! Thanks for your reply :)

- forgot to mention that I tested on Neos v3.3.12 with UI v1.2.2
- Underline and strikethrough: had enabled all possible "aloha" options
- spell check: "old" ckeditor has an attribute `spellcheck="false"` set

**Comment by dimaip** [comment]
@KPeschke 
This seems to work for me:
```
      ui:
        aloha:
          'format':
            'underline': true
            'strikethrough': true
```
Though maybe this change is still in master and not 1.2.2.

Regarding spellchecker, could be cool to be able to enable it, but we don't know the content's language...

**Comment by dimaip** [comment]
Please leave your test feedback here from now on: https://github.com/neos/neos-ui/issues/2002

**Pull request merged**
