### PR TITLE
TASK: Renames isEmpty helper to isNil

### PR DESCRIPTION
**Pull request by markusguenther**
This is a change related to the issue #3070
In the PR #3069 we discussed after merge that the naming could be different.

Therefore, we rename the helper now afterwards.

### CODE REVIEW

**Comment by Sebobo** [comment]
Name is definitely better. But I wonder why an empty string is considered as "not set".
Also why does it iterate over the keys and return false if a key exists?

**Comment by jonnitto** [comment]
Should the naming not be something like `isOptionNotSet`? `isOptionSet(['Jon Doe'])` return `false` Otherwise, `true` and `false` need to be switched

**Comment by mhsdesign** [comment]
> Also why does it iterate over the keys and return false if a key exists?

as far as i know its not too easy to find out if a js object is empty `{} === {}` wont work for example ...

**Comment by mhsdesign** [comment]
btw i feel like we are all nitpicking over a total overengineer solution (https://github.com/neos/neos-ui/pull/3069)

**-** and by saying this im probably nitpicking the solution 😁

**Comment by Sebobo** [comment]
This is sadly a very important but dangerous method that needs to be thoroughly defined, documented and changing it later will be super breaky. So its important to have several people nitpick :)

**Comment by markusguenther** [comment]
Ok, as already asked in the PR before, maybe `isNil` is enough. It solves the initial error and does not that much magic as mentioned before. Hope that can help with all the concerns :)

**Review by mhsdesign — APPROVED** [review]
Thanks for your effort 👍

**Review by Sebobo — APPROVED** [review]

**Comment by markusguenther** [comment]
That merge was too quick. The tests were red because when the value is an empty string, it does not behave the same now.
So will have another PR as bug fix ;)

**Comment by mhsdesign** [comment]
we can also 'revert'

**Pull request merged**
