### PR TITLE
FEATURE: Add new Icons from fontawesome

### PR DESCRIPTION
**Pull request by markusguenther**
Upgrading from version 5.8.0 to 5.12.0.
This adds lots of new icons.

### CODE REVIEW

**Comment by Sebobo** [comment]
Cannot test it because of https://github.com/neos/neos-ui/issues/2654

**Comment by Sebobo** [comment]
Do those icons btw. also work in the backend modules properly?

**Comment by markusguenther** [comment]
@Sebobo In the react based paert you can use the new Icons with this PR and for the non react Modules I have the other PR (https://github.com/neos/neos-development-collection/pull/2881)

Would be nice to have only one source at some time but it is not that easy.

**Comment by markusguenther** [comment]
@Sebobo Thanks for the hint. Already updated it :)

**Pull request merged**
