### PR TITLE
TASK: Upgrade moment.js to version 2.19.2

### PR DESCRIPTION
**Pull request by markusguenther**
The current used version 2.14.1 is marked as insecure.
Therefore it would be good to upgrade the package.

Fixes: #1359

### CODE REVIEW

**Comment by markusguenther** [comment]
Restart TravisCI

**Comment by markusguenther** [comment]
We don`t use the call moment.duration in combination with the format function. So first need to investigate were it really occurs and come from. :/

**Comment by markusguenther** [comment]
Need to setup my local neos again ... because ee tests are actually falling for me in master. So something is wrong... but will update this soon.

**Comment by mstruebing** [comment]
I think I've found something regarding this issue:

```
$ grep -Hnir 'this.moment.duration'
node_modules/testcafe-reporter-list/lib/index.js:94:            var durationStr = this.moment.duration(durationMs).format('h[h] mm[m] ss[s]');
node_modules/testcafe-reporter-spec/lib/index.js:95:            var durationStr = this.moment.duration(durationMs).format('h[h] mm[m] ss[s]');
```

So, testcafe needs an update that we can update `moment.js`

**Comment by markusguenther** [comment]
Just updating test-cafe ist not enough ... but I am on track ;)

**Comment by markusguenther** [comment]
Ok since testcafe had the problems I submitted PRs to the testcafe repositories.
Hope that they get merged soonish and find the way into a new release.
Otherwise this is blocked for a while ;)

https://github.com/DevExpress/testcafe-reporter-spec/pull/4
https://github.com/DevExpress/testcafe-reporter-list/pull/4

**Pull request closed without merging**
