### PR TITLE
TASK: Resolve Javascript warning is in the console

### PR DESCRIPTION
**Pull request by markusguenther**
The react-slick component has an issue with plain HTML arrows. The solution is to use react components as wrappers.

### CODE REVIEW

**Comment by markusguenther** [comment]
The warnings are gone. But I need to polish the PR a bit and maybe @dimaip or @mstruebing give a opinionated comment regarding creation a component in our package or just create a component in the EditPane folder because it is actually only used there?

Because when I make it as regular component I will also create storybook stuff and so on.

**Comment by dimaip** [comment]
Yeah it doesn't make a lot of sense to put it as a reusable component IMO, I would just create it inline.

**Comment by dimaip** [comment]
But up to you to judge

**Comment by mstruebing** [comment]
If it is only used there and don't even considered to be reused it should be in EditPane in my opinion.

**Comment by mstruebing** [comment]
What about this @markusguenther? :)

**Comment by markusguenther** [comment]
Warnings has been resolved but the buttons does not work anymore. Need to adjust that.

**Comment by markusguenther** [comment]
I finally made it to update this PR. Sorry that it took so long.

**Comment by markusguenther** [comment]
Ah and think forgot to mention that this fixes #1804

**Pull request merged**
