### PR TITLE
TASK: Upgrade slugify to version 1.1.0

### PR DESCRIPTION
**Pull request by markusguenther**
**What I did**
Upgraded slugify to the latest version

**How to verify it**

Change the page title to a for instance Cyrillic name and update the uri path segment.
We also have a test for that in out end to end tests ;)

### CODE REVIEW

**Comment by markusguenther** [comment]
Tests are fine ... the styleCI stuff is unrelated.

**Comment by dimaip** [comment]
Could you please apply the suggested patch? We need to get the tests back to green.

**Comment by markusguenther** [comment]
> Could you please apply the suggested patch? We need to get the tests back to green.

Hi @dimaip what do you mean with suggested patch? The StyleCI stuff? To be honest don't get it why they always change their base and suggest changes you did not touch in your PR.

**Comment by dimaip** [comment]
@markusguenther yeah, the styleci one.
I don't know either, but it's the way it works, it just spontaneously complains about untouched parts of code for whatever reason...
So we either remove styleci altogether or keep on applying their patches when they popup. I'm against just ignoring them.

**Comment by markusguenther** [comment]
With the updated and cleaned up CI pipeline this is now green again ;)

**Pull request merged**
