### PR TITLE
TASK: Extract job ID from saucelabs

### PR DESCRIPTION
**Pull request by markusguenther**
## Description

This pull request addresses issue #2762.

In our end-to-end tests, we currently leverage Sauce Labs for recording video. However, the video link is accessible only to team members, limiting visibility for non-team members. To enhance transparency and allow contributors to view the recording without the need for local setup, this pull request introduces a script or GitHub Action.

The script or action automates the process of extracting the Sauce Labs video link and posts it as a comment on the corresponding pull request. With this enhancement, non-team members can easily access and review the video recording, gaining valuable insights into the end-to-end test results.

### Changes Made

  * Added a script to extract the Sauce Labs video link.
  * Integrated the script to automatically comment on the pull request with the video link via CircleCI
  * The comment will be updated when the pipeline rerun and generates new recordings

### CODE REVIEW

**Comment by markusguenther** [comment]
Hi from outa space CLI

**Comment by markusguenther** [comment]
Linked recordings of the acceptance tests: \n - https://app.saucelabs.com/rest/v1/jobs/22ff7cda2d0340178809a614440f7fc4/video.mp4 \n - https://app.saucelabs.com/rest/v1/jobs/455b5279650a435bbe2965035d9b58f8/video.mp4

**Comment by markusguenther** [comment]
Linked recordings of the acceptance tests: \n - https://app.saucelabs.com/rest/v1/jobs/22ff7cda2d0340178809a614440f7fc4/video.mp4 \n - https://app.saucelabs.com/rest/v1/jobs/455b5279650a435bbe2965035d9b58f8/video.mp4

**Comment by markusguenther** [comment]
🎥 **Linked recordings of the acceptance tests :** 🎥 \n * https://app.saucelabs.com/rest/v1/jobs/22ff7cda2d0340178809a614440f7fc4/video.mp4 * https://app.saucelabs.com/rest/v1/jobs/455b5279650a435bbe2965035d9b58f8/video.mp4

**Comment by markusguenther** [comment]
🎥 **Linked recordings of the acceptance tests :** 🎥\n * https://app.saucelabs.com/rest/v1/jobs/22ff7cda2d0340178809a614440f7fc4/video.mp4 * https://app.saucelabs.com/rest/v1/jobs/455b5279650a435bbe2965035d9b58f8/video.mp4

**Comment by markusguenther** [comment]
🎥 **Linked recordings of the acceptance tests :** 🎥%d\n * https://app.saucelabs.com/rest/v1/jobs/22ff7cda2d0340178809a614440f7fc4/video.mp4 %d\n * https://app.saucelabs.com/rest/v1/jobs/455b5279650a435bbe2965035d9b58f8/video.mp4 %d\n

**Comment by markusguenther** [comment]
🎥 **Linked recordings of the acceptance tests :** 🎥\n * https://app.saucelabs.com/rest/v1/jobs/22ff7cda2d0340178809a614440f7fc4/video.mp4 * https://app.saucelabs.com/rest/v1/jobs/455b5279650a435bbe2965035d9b58f8/video.mp4

**Comment by markusguenther** [comment]
🎥 **Linked recordings of the acceptance tests :** 🎥

* https://app.saucelabs.com/rest/v1/jobs/22ff7cda2d0340178809a614440f7fc4/video.mp4
* https://app.saucelabs.com/rest/v1/jobs/455b5279650a435bbe2965035d9b58f8/video.mp4

**Comment by markusguenther** [comment]
Neuer comment

**Comment by markusguenther** [comment]
foo

**Comment by markusguenther** [comment]
foo

**Comment by markusguenther** [comment]
foo

**Comment by markusguenther** [comment]
🎥 **Linked recordings of the acceptance tests :** 🎥

* https://app.saucelabs.com/rest/v1/jobs/22ff7cda2d0340178809a614440f7ds3/video.mp4
* https://app.saucelabs.com/rest/v1/jobs/455b5279650a435bbe2965035d9b58f8/video.mp4

**Comment by markusguenther** [comment]
🎥 **End-to-End Test Recordings**



These videos demonstrate the end-to-end tests for the changes in this pull request.

**Comment by markusguenther** [comment]
🎥 **End-to-End Test Recordings**



These videos demonstrate the end-to-end tests for the changes in this pull request.

**Comment by markusguenther** [comment]
🎥 **End-to-End Test Recordings**



These videos demonstrate the end-to-end tests for the changes in this pull request.

**Comment by markusguenther** [comment]
🎥 **End-to-End Test Recordings**


* [Recording 1](https://app.saucelabs.com/rest/v1/jobs/22ff7cda2d0340178809a614440f7ds3/video.mp4)
* [Recording 2](https://app.saucelabs.com/rest/v1/jobs/455b5279650a435bbe2965035d9b58f8/video.mp4)

These videos demonstrate the end-to-end tests for the changes in this pull request.

**Comment by markusguenther** [comment]
🎥 **End-to-End Test Recordings**


* [Recording 1](https://app.saucelabs.com/rest/v1/jobs/22ff7cda2d0340178809a614440f7ds3/video.mp4)
* [Recording 2](https://app.saucelabs.com/rest/v1/jobs/455b5279650a435bbe2965035d9b58f8/video.mp4)

These videos demonstrate the end-to-end tests for the changes in this pull request.

**Comment by markusguenther** [comment]
Test

**Comment by markusguenther** [comment]
> Test

**Review by mhsdesign — APPROVED** [review]
Thank you so much. Thanks that you went thought that shell hell for us. I would have probably taken 1 hour for every shell line 😂 How do you do this???

**Comment by markusguenther** [comment]
> Thank you so much. Thanks that you went thought that shell hell for us. I would have probably taken 1 hour for every shell line 😂 How do you do this???

As you see, the commits has been force pushed several times and I needed lots of commits :D
But even when it was not so funny at some point, I wanted to finish it as I spent already so much time ;)

**Comment by mhsdesign** [comment]
This is just ci and stuff. We wont be needing it for development as we dont develop on 7.3 anymore. So id say 8.3 should be it ;)

**Comment by markusguenther** [comment]
However, I would like to explain why I think this PR is still useful and important. As you know, we still need to provide security patches for this branch, even though we are not actively developing new features or fixing bugs. For that purpose, it is helpful to have a reliable and fast way to run the tests and check the results. It also does not hurt to have it and is easy to upmerge.

**Comment by mhsdesign** [comment]
Okay then let’s do it ;) I will not oppose any further.

**Comment by mhsdesign** [comment]
Hu but this caused a sideeffect that made the tests actually _harder_ to read. I triggered now 5 test runs until i found out that the logs are written to `app/Data/Logs/AcceptanceTesting.log`. That is clever but not visible to the human eye :D

Also it seems the links were dead for the last prs i tried this feature on, sorry to inform you about that :/

**Comment by mhsdesign** [comment]
Yes not seeing the current progress it a bit of a bummer, i would vouch for putting it into the log BUT most importantly keeping the output as it happens on the cli.

Also it seems the feature doesnt work any longer since a month now, maybe its too complex to maintain for us?

Having the github bot create a comment and stuff is great, but if its more stable to post the link to the recordings at the end of the run in the console output i would really like that.

Especially as the comments got me hyped into thinking someone reviewed my pr, but it was just the bot :O

**Comment by mhsdesign** [comment]
Could you please revert this, or am i allowed to do so? ^^ As it A doesnt work and B obscures the logs and makes things harder to understand. Sorry that your effort dint pay out. But it guess this is just a too big complexity with relatively little gain?
... a Neos Ui stage would be another thing ...

**Comment by mhsdesign** [comment]
has been reverted via https://github.com/neos/neos-ui/commit/d5b9dbab016812bfb2c17708923027a83c0ee634 but unfortunately the introduction of sauce cli makes it a little harder to get the testcafe console log in https://github.com/neos/neos-ui/pull/3911 im attempting to reinstate that.

**Pull request merged**
