### PR TITLE
FIX: correct plugin view

### PR DESCRIPTION
**Pull request by beardcoder**

### CODE REVIEW

**Comment by markusguenther** [comment]
Was related to #2384

**Comment by dimaip** [comment]
Awesome! But guys, please, follow our commit naming guidelines when merging. E.g. it has to be one of BUGFIX/TASK/FEATURE.

**Comment by markusguenther** [comment]
@dimaip Yes my fault... say it after it happend :/

**Comment by dimaip** [comment]
No problem at all just a nitpick

**Pull request merged**
