### PR TITLE
TASK: Make the content UI a backend module with its own module privilege

### PR DESCRIPTION
**Pull request by daniellienert**
Define the Neos.Ui as real Neos backend module with its own privilege.
Refactor the backend menu generation and exchange custom implementations with Neos API and standard Fusion.

# Todo:

- [x] Remove the duplicate code, that renders the backend menu in fusion 

Needed to solve https://github.com/neos/neos-development-collection/issues/2351
Relates to: https://github.com/neos/neos-development-collection/pull/3123
Relates: #2798

### CODE REVIEW

**Comment by markusguenther** [comment]
Thanks for taking care in that area @daniellienert ... will not make it to check it this week, as I concentrate on getting the new release (4.x and newer) on the street. But will check it next week :) 
 ❤️

**Review by kdambekalns — APPROVED** [review]
Read through the change (did not test), and I love it. So much deleted code, awesome! 🎉

**Comment by bwaidelich** [comment]
Awesome, thanks for taking care!
I need to wrap my head around this one, but the statistics look great already
image
:)

Two questions already though:
1. You delete 6 Fusion implementations/helpers. Is that really related to this feature? Otherwise I would suggest to move them to a separate PR in order to make this one easier to review and less likely to break things along the way :)
2. Is the failing e2e test related?

**Comment by daniellienert** [comment]
@bwaidelich, I guess the e2e tests are related but need the Neos counterpart merged to get green

**Review by markusguenther — APPROVED** [review]
Thanks @daniellienert for bringing that up. I have tested the PR together with the neos related PR locally and also tried the e2e test locally.

**Comment by daniellienert** [comment]
@markusguenther help :) I merged the Neos part and restarted the tests here. From what I understand, the failing tests are not related to this change? If not, this should also be merged, as master might be broken in the current state

**Comment by markusguenther** [comment]
@daniellienert Started the tests again and if even a rerun from start fails. Will check that locally.
But as it is master we can also fix the e2e test later but soon.

**Comment by daniellienert** [comment]
@markusguenther 🤷🏻‍♂️

**Comment by dimaip** [comment]
Guys, to debug the tests the first thing you should do is to watch the video: https://app.saucelabs.com/tests/77bf1948dc3c44459ab26e229a730e64#1
E.g. in this case apparently there's some 404 error for some reason. What could this be? Another upmerge issue?

**Comment by markusguenther** [comment]
Tested that now locally and it works also with the e2e tests.

**Comment by dimaip** [comment]
You are my hero @markusguenther, thank you!

**Comment by markusguenther** [comment]
@dimaip I don't feel like a hero ;)

Tried to change the circle ci stuff yesterday with a new docker container with php 7.4. ;) 
So that master tests are using the php 7.4 container...

**Pull request merged**
