### PR TITLE
FEATURE: Remove neos-ui-ckeditor-bindings and ckeditor 4

### PR DESCRIPTION
**Pull request by markusguenther**
**What I did**
This PR removes the compatibility layer of the CKEditor to be able to run Neos in the old Internet-Explorer 11.
The whole CKEditor 4 bindings will be removed and the `defaultInlineEditor` configuration is removed.

We now use only the CKEditor in version 5.

Relates: #2855

### CODE REVIEW

**Review by jonnitto — APPROVED** [review]
Nice. Less code == faster

**Comment by markusguenther** [comment]
Updated to the latest state of master

**Comment by markusguenther** [comment]
> wtf 416 files 😂 i guess i can only see if it works by testing it
> 
> one can find out what actually changed by unticking Deleted files:
> 
> image

Yeah, as this removes the whole CKEditor version 4 stuff it is a lot.
The packages path from the CKEditor binding can be excluded as this has been removed and the assets from the resource folder. So the more important part is where the switch of the versions take place.

**Comment by mhsdesign** [comment]
so this basically removes this whole `setDefaultInlineEditor` api - that one can change the editor right?
then the node yaml schemas should also be updated - if they exist ^^

**Comment by markusguenther** [comment]
> `setDefaultInlineEditor`

Yes, when this is merged, we also need to check docs for that config.

**Comment by markusguenther** [comment]
@mhsdesign did you find something while the review? Or can you also approve this change?

**Review by mhsdesign — APPROVED** [review]
i still wanted to test this out locally - sorry for keeping you waiting ^^ - conceptionally i a can approve already

**Comment by markusguenther** [comment]
I resolved the conflicts again. And if you want to try it locally feel free to test this first.
Don't want to push you to an approval.

**Pull request merged**
