### PR TITLE
TASK: Remove useless return

### PR DESCRIPTION
**Pull request by mstruebing**
related https://github.com/neos/eslint-config-neos/pull/16

### CODE REVIEW

**Comment by mstruebing** [comment]
Basically: eslint was updated by @markusguenther which introduced and adjusted many rules, no one cares about our linter setup and I wanted to remove any linter warning which isn't a `TODO`-warning (reducing linter noise) but @dimaip proposed to adjust the rules to our needs :)

**Comment by dimaip** [comment]
Yeah I would adjust the rules when I have the time and inspiration for such work :)
Or somebody else could take care as well.

**Comment by dimaip** [comment]
I would be so much in favor of prettier, but also there were some people against it, but I could not possibly bash about code style and linting tools (getting old, eh?)

**Comment by mstruebing** [comment]
@dimaip @markusguenther is this helpful for further adjustments or can I close this PR?

**Pull request closed without merging**
