### PR TITLE
TASK: Upgrade webpack to version 4

### PR DESCRIPTION
**Pull request by markusguenther**
Next try ;)

Updates:

* webpack to version 4.29.1
* webpack-merge to version 4.1.5
* webpack-livereload-plugin to version 2.2.0
* json-loader to 0.5.7
* css-loader to 2.1.0
* postcss-hexrgba to 1.0.1
* postcss-import to 12.0.1
* postcss-loader to 3.0.0
* ts-loader to 5.3.3

Adds

* webpack-cli in version 3.2.3
* uglifyjs-webpack-plugin in version 2.1.1
* mini-css-extract-plugin 0.5.0

Removes

* extract-text-webpack-plugin

Resolves: #1654

### CODE REVIEW

**Comment by dimaip** [comment]
So what's up with this? Does it really just work?! Merge ready? :)

**Comment by dimaip** [comment]
Also, did you test neos-ui-extensibility?

**Comment by markusguenther** [comment]
@dimaip @Sebobo We just tested the extensibility with the yoast neos package. It works when you add the mini-css-extract-plugin dependency manually so that you fill the gap of the release. 

So now we need to merge it and wait for a release. It worked in the yoast package and the regular backend.

**Comment by dimaip** [comment]
Ok, let's merge and test more extensively during the sprint, then do the release and test the extensibility.

**Pull request merged**
