### PR TITLE
9.0: Adjust to changed node path API

### PR DESCRIPTION
**Pull request by nezaniel**
This adjusts the usage of node paths to the changes in https://github.com/neos/neos-development-collection/pull/4339

### CODE REVIEW

**Review by mhsdesign — COMMENTED** [review]
By reading, but there are wo but's:

- we should make a follow up todo as discussed to ban these usages (maybe via findByAncestor)
- we must wait for https://github.com/neos/neos-development-collection/pull/4339 to be merged to get green tests ^^

**Review by grebaldi — APPROVED** [review]
:+1:  by reading

**Comment by bwaidelich** [comment]
I can confirm that this PR is required for Neos to work on latest 9.0 branch 🚀 
@mhsdesign can you clarify what you meant by

> we should make a follow up todo as discussed to ban these usages (maybe via findByAncestor)

ban the usages of `ContentSubgraphInterface::findNodeByPath()` and `ContentSubgraphInterface::retrieveNodePath()`?

**Review by bwaidelich — APPROVED** [review]

**Comment by mhsdesign** [comment]
yes @bwaidelich , this was a comment before https://github.com/neos/neos-ui/pull/3530/commits/0cd102445dc0fb766a43d7404fc7d68d17e7ef8c

**Pull request merged**
