### PR TITLE
TASK: Update to FontAwesome 5.2

### PR DESCRIPTION
**Pull request by mstruebing**
Current state:

```
TypeError: definition is undefined
```

which occurs while calling the `library.add` function in `packages/react-ui-components/src/Icon/index.js`

Related to #2028

### CODE REVIEW

**Comment by h1Modeling** [comment]
I think you should do something like:

import { far } from '@fortawesome/free-regular-svg-icons'
import { fas } from '@fortawesome/free-solid-svg-icons'
import { fab } from '@fortawesome/free-brands-svg-icons'

library.add(far, fas, fab)

I hope this helps ?!

**Comment by h1Modeling** [comment]
@mstruebing 
I got it working with the proposed change and 
`import {FontAwesomeIcon} from '@fortawesome/react-fontawesome';`
in` icon.js`

**Comment by mstruebing** [comment]
Thank you @h1Modeling - credit goes to you

**Comment by mstruebing** [comment]
This is ready now:

icon

**Comment by dimaip** [comment]
Cool work, guys!

**Pull request merged**
