### PR TITLE
BUGFIX: only allow to create nodes of the same role as the reference node

### PR DESCRIPTION
**Pull request by dimaip**
Fixes: #766

### CODE REVIEW

**Comment by skurfuerst** [comment]
Hm, need to investigate wyh this is the case; actually this has worked before I am quite sure

**Comment by dimaip** [comment]
Hmm again I can not reproduce, sorry! Can you post an example NodeTypes.yaml snippet and exact description how to reproduce it.
I checked it with Sfi.Grid extension: https://github.com/psmb/Sfi.Grid/blob/master/Configuration/NodeTypes.yaml

image

**Comment by dfeyer** [comment]
I can do more test later today

**Comment by dimaip** [comment]
@dfeyer Can you also test if it was my changed that broke it for you or not. Because if not we can just merge this one.

**Pull request merged**
