### PR TITLE
Update eslint to version 4

### PR DESCRIPTION
**Pull request by markusguenther**
Need to wait for the PR in the sub repository of neos-project/eslint-config-neos.

Fixes: #1511

### CODE REVIEW

**Comment by markusguenther** [comment]
Trigger travis again

**Comment by markusguenther** [comment]
Hmm locally it works :/

bildschirmfoto 2018-01-02 um 08 42 04

**Comment by markusguenther** [comment]
Tried it and wrote a comment on the @neos-project/eslint-config-neos repository.

Options are listed here:
https://eslint.org/docs/rules/padded-blocks

**Comment by markusguenther** [comment]
@mstruebing This was not completed yet ;)

We first need a new version of the library eslint-config-neos.

See: 

```
"@neos-project/eslint-config-neos": "git://github.com/markusguenther/eslint-config-neos.git#update-eslint",
```

**Comment by markusguenther** [comment]
So the master now has a dependency on my fork ;)

**Comment by mstruebing** [comment]
Fixing it right now :D

**Pull request merged**
