### PR TITLE
Add missing hover states (#1471)

### PR DESCRIPTION
**Pull request by danielkestler**
Added some important hover states for publish dropdown and publish button bottom right, see:
https://github.com/neos/neos-ui/issues/1471

bildschirmfoto 2018-10-17 um 12 09 07

### CODE REVIEW

**Comment by dimaip** [comment]
Just curious, couldn't the same effect be achieved by `opacity` or by any other CSS property.
If not, then I think your approach is fine. It might just get a little hard to maintain once we have more colors.

**Comment by danielkestler** [comment]
Well, you won't get the exact same color. Also not possible using lighten() or similar, because this changes perceived saturation (and does not work using --var-colors-).

I think my changes are just a "quick win". We should rethink hover states in general from a design perspective. For example, the hovering of "dark" elements (like the slide toggles) with the primary blue color is quite heavy – and my hover effects of this PR are much more decent. And what about all those other elements (nodes in the page tree, all those dropdowns and input fields ...)?

**Comment by danielkestler** [comment]
Planning to contribute more in this direction. But I don‘t know where is the right place to discuss design changes – or better „just do it“ in a PR?

**Comment by mstruebing** [comment]
A PR is always helpful because it already shows in detail what you mean - but if you have more general topics there is a `#guild-ux` channel on slack.

**Comment by dimaip** [comment]
Hah, the best place to discuss changes is a code sprint! We got one coming up in November, so perhaps you'd want to join @danielkestler?
Other than that, as Max said: #guild-ux or discuss.neos.io. But in practice discussions around existing PRs seem to be the most concrete and fruitful.

**Pull request merged**
