### PR TITLE
  TASK: Remove Grid component

### PR DESCRIPTION
**Pull request by dfeyer**

### CODE REVIEW

**Comment by dfeyer** [comment]
If you agree we can remove this component completly, most of the time it can be replace by CSS flexbox

**Comment by dfeyer** [comment]
Most of the time the Grid / Grid.Col component can be removed, and replace by CSS flexbox

**Comment by mstruebing** [comment]
@dfeyer  Please rebase your branch against the latest master, the master is repaired so that travis will run through if everything is fine

**Comment by mstruebing** [comment]
Sorry for closing, but I was on repairing the tests when I realized that I can't push to your branch. (Allow edit from maintainers not allowed?)
https://github.com/neos/neos-ui/pull/1582

I've included your commits, and added the one to repair the e2e tests.
https://github.com/neos/neos-ui/pull/1582/commits/267d0bfc268c34f86e2cf344b7468b56ebc6327e

**Pull request closed without merging**
