### PR TITLE
TASK: Upgrade to FontAwesome 6.5.2

### LINKED ISSUE #3793: FEATURE: upgrade FontAwesome to latest version (6.5.2)
### Description

It is time to upgrade FontAwesome again, so we can use the latest Icons, etc.

The current latest version is 6.5.2 as of the 1st of June 2024.

### Possible Solution
The major upgrade documentation can be found here: https://docs.fontawesome.com/web/setup/upgrade/

Maybe this old PR from 5.8.2 can give a bit of insight aswell: https://github.com/neos/neos-ui/pull/2487/files

### PR DESCRIPTION
**Pull request by wiegandj**
Issue: https://github.com/neos/neos-ui/issues/3793

Upgraded FontAwesome in neos-ui to 6.5.2.

Versions were tested in neos-development-collection before.

See upgrade for neos-development-collection:
Issue: https://github.com/neos/neos-development-collection/issues/5107
PR: https://github.com/neos/neos-development-collection/pull/5108

### CODE REVIEW

**Comment by ahaeslich** [comment]
@wiegandj can you please rebase this change onto the 8.4 branch. This way no unrelated commits will show up in your PR.

**Review by Sebobo — APPROVED** [review]
I had to ignore some type related issues with our FA Icons component. We can either merge it like this and fix this separately or find a fix. 
The TS error message was too convoluted for me to understand right now.

Ping @grebaldi @markusguenther @mhsdesign maybe one of you can understand the error.

**Comment by grebaldi** [comment]
@Sebobo 
> I had to ignore some type related issues with our FA Icons component. We can either merge it like this and fix this separately or find a fix.
> The TS error message was too convoluted for me to understand right now.

Our `IconProps` extend the `FontAwesomeIconProps` imported from `@fortawesome/react-fontawesome`. Since https://github.com/FortAwesome/react-fontawesome/commit/e32a0cbc2d3c944e6cdc6d63d32ca1e275de6e43 (so, v0.2.0 of `@fortawesome/react-fontawesome`) `FontAwesomeIconProps` extends `RefAttributes<SVGSVGElement>`, which implies the following definition for a `ref` prop:

```typescript
{
  ref?: Ref<SVGSVGElement>
}
```

This definition collides with the intrinsic `ref` prop that is defined for every class component, in the case of our `FontAwesomeIcon` component that would be:

```typescript
{
  ref?: LegacyRef<FontAwesomeIcon>
}
```

This can be easily fixed by adjusting the type definition for our `IconProps` (in https://github.com/neos/neos-ui/blob/18758688f6f258b4dbb54aab8f91c0c2feba02e1/packages/react-ui-components/src/Icon/icon.tsx#L27) thusly:

```diff
-export interface IconProps extends Omit<FontAwesomeIconProps, 'icon'> {
+export interface IconProps extends Omit<FontAwesomeIconProps, 'icon' | 'ref'> {
```

If it's easier, I think it'd be okay to do this post-merge. But this branch needs a rebase anyway.

**Comment by Sebobo** [comment]
I rebased, solved conflicts and fixed the type issue like you described @grebaldi, thx a lot!
I also found that icons in dropdowns were suddenly to large as the font awesome class `fa-w-16` does not exist anymore (so much for not breaking). So I had to fix that in the places I found.

**Review by grebaldi — APPROVED** [review]
Thanks for taking care of the update, @wiegandj! And thanks for rebasing and solving conflicts @Sebobo!

I updated the failing snapshot test and fixed the icon reference in that one E2E test case. Everything should be green when CI is done.

**Pull request merged**
