### PR TITLE
TASK: Remove showInvisible query parameter

### PR DESCRIPTION
**Pull request by kdambekalns**
The correct preview of a hidden document is not showing it, after all…

See #2500

### CODE REVIEW

**Comment by kitsunet** [comment]
Mmm, should we talk about this whole topic again, and think about the usecase(s) and look at what we want and wanted with this change. I know we talked about this before, but maybe now with more information we can look at it again.

**Comment by markusguenther** [comment]
For some reason i have no permission to rerun the cirecle ci tests :(

**Comment by gerhard-boden** [comment]
> For some reason i have no permission to rerun the cirecle ci tests :(

me neither, maybe it has something to do with running the e2e tests on Karsten's fork?

**Comment by markusguenther** [comment]
When I am back home need to test it locally.

**Comment by markusguenther** [comment]
By reading it should work

**Comment by dimaip** [comment]
Wow, even I don't have permissions. I wonder why.

**Comment by dimaip** [comment]
Anyways, merged it as is.

**Pull request merged**
