### PR TITLE
BUGFIX: 3531 node creation dialog prevent accidental close

### LINKED ISSUE #3531: BUG: Click outside of the node creation dialog closes the dialog
I think making this decision is to simple and a bit unexpected user behavior. If you fill out a more complex dialog and accidentally click into the darkened space around, it is immediately closed without asking what to do with the pending changes.

I would rather:
A: Do nothing (one should use the escape key or the "back" button)
B: Show an popup warning that we will now proceed to close

... Fun fact, due to my nervous clicking, this bit me in a customer presentation ^^

### PR DESCRIPTION
**Pull request by mhsdesign**
resolves: #3531

discussion happening in the issue ;)

https://github.com/neos/neos-ui/assets/85400359/ab29bdeb-5fc2-4995-ac00-b4c238ad1a38

**What I did**

**How I did it**

**How to verify it**

### CODE REVIEW

**Review by Sebobo — CHANGES_REQUESTED** [review]
Awesome tiny change, but I think an editor needs some feedback, why they cannot escape the dialog anymore except when pressing "back" 😉

So either visual feedback, dialog in dialog, something, not sure what's best

**Review by crydotsnake — APPROVED** [review]
Works great. I like it! :)

**Review by jonnitto — APPROVED** [review]

**Review by Sebobo — APPROVED** [review]

**Comment by mhsdesign** [comment]
As [written](https://github.com/neos/neos-ui/issues/3531#issuecomment-1630535077) in the issue, id rather go with https://github.com/neos/neos-ui/pull/3579 and close this ;)

**Comment by mhsdesign** [comment]
closing in favor of #3579

**Pull request closed without merging**
