### PR TITLE
BUGFIX: Fix module path in package.json

### PR DESCRIPTION
**Pull request by Sebobo**

### CODE REVIEW

**Comment by mhsdesign** [comment]
nenennenennennen das mach ich schon :)

**Comment by Sebobo** [comment]
What do you mean?

**Comment by mhsdesign** [comment]
ups hab den diff falsch gelesen

**Comment by markusguenther** [comment]
English please 🙃

**Comment by Sebobo** [comment]
So is this fix now correct or not?
The referenced file before does not exist and my IDE also complained about it.

**Comment by mhsdesign** [comment]
hmm yes i tried to understand why ci fails ... it seems pretty much correct... odd that i missed this at all

(thanks for noticing and trying to fix it)

**Comment by markusguenther** [comment]
> hmm yes i tried to understand why ci fails ... it seems pretty much correct... odd that i missed this at all

It is not just CI. You can see that locally as well!

**Comment by mhsdesign** [comment]
I give up for now ... i couldnt fix it ...

i tried various typescript settings (https://www.typescriptlang.org/tsconfig#moduleResolution to Node16 Node12 NodeNext) upgraded typescript from 4.7 (now) to 4.9 and set  other useless options in the tsconfig ...

i think, we might be able to fix this one case manually by telling typescript where to find the array sorter, but that defeats the purpose of yarn workspaces.

So ultimately we want to fix
> typescript yarn workspaces cannot find module


hmmm wow:
> "main": "./src/positionalArraySorter.ts",
works too - but we want to distribute cjs and esm at the same time no? https://github.com/neos/neos-ui/issues/3262

**Comment by markusguenther** [comment]
Thanks for this fix.

Tried it locally and the tests say that everything is fine, but we have some console errors inside the tests.
Checked the last 8.1 run and there were not console.errors. (https://app.circleci.com/pipelines/github/neos/neos-ui/2764/workflows/8c1dd7b7-268d-430f-9ccf-07eab162ff0c/jobs/12663)

For instance this one.
Screenshot 2022-12-02 at 22 30 27

**Comment by markusguenther** [comment]
But these `console.errors` are not related to that change. So this helps to bring us forward :)
Also tested now with `"@neos-project/positional-array-sorter": "^8.2.1"` as dependency in the extensibility instead of the 8.1.4

**Comment by markusguenther** [comment]
Created an issue for the errors, so that we don't miss it https://github.com/neos/neos-ui/issues/3288

**Comment by mhsdesign** [comment]
thx for all the testing.
see #3258 for tge console errors ;)

**Pull request merged**
