### PR TITLE
TASK: Increase PHP version for CircleCI

### PR DESCRIPTION
**Pull request by markusguenther**
We now use PHP version 8.0 as minimal version. So we need to adjust the CircleCI images.

### CODE REVIEW

**Comment by kdambekalns** [comment]
That error is from

```php
        $this->classReflectionData[$interfaceName][self::DATA_INTERFACE_IMPLEMENTATIONS][$className] = true;
```

if I am looking at the right version of the code. So the reflection data is not an array, as expected, but a probably a boolean `false` or `null`. 🤔

Side note:
> You’re using a [deprecated Docker convenience image.](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034) Upgrade to a next-gen Docker convenience image.

looks like it wants to be solved.

**Comment by mficzel** [comment]
This is the line https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/Reflection/ReflectionService.php#L1385

**Comment by kdambekalns** [comment]
I tried to re-run with SSH, but get some rather cryptic message about a missing SSH key. 🤷‍♂️

**Comment by markusguenther** [comment]
We had the idea to use `composer update` instead of the `package:rescan` sadly with the same outcome.
Will check later this evening, thanks for all the input in slack and here 💙

**Comment by kdambekalns** [comment]
> In the Project settings you are able to add user keys from Github

Not the key I need, or at least not the one I want. *I* have a private key and want to to log in to the build machine…

**Comment by kdambekalns** [comment]
At least CircleCI shows the artifacts, and there I see:

```
Exception in line 1264 of /home/circleci/app/Packages/Framework/Neos.Flow/Classes/Reflection/ReflectionService.php: Cannot use a scalar value as an array

23 Neos\Flow\Reflection\ReflectionService::addImplementedInterface("Neos\TestNodeTypes\NodeCreationHandler\ImagePropertyNodeCreationHandler", Neos\Flow\Reflection\ClassReflection)
22 Neos\Flow\Reflection\ReflectionService::reflectClass("Neos\TestNodeTypes\NodeCreationHandler\ImagePropertyNodeCreationHandler")
21 Neos\Flow\Reflection\ReflectionService::Neos\Flow\Reflection\{closure}("Neos\TestNodeTypes\NodeCreationHandler\ImagePropertyNodeCreationHandler")
20 array_filter(array|1|, Closure)
19 Neos\Flow\Reflection\ReflectionService::reflectEmergedClasses()
18 Neos\Flow\Reflection\ReflectionService::buildReflectionData(array|19|)
17 Neos\Flow\ObjectManagement\CompileTimeObjectManager::initialize(array|124|)
16 Neos\Flow\Core\Booting\Scripts::initializeObjectManagerCompileTimeFinalize(Neos\Flow\Core\Bootstrap)
15 call_user_func(array|2|, Neos\Flow\Core\Bootstrap)
14 Neos\Flow\Core\Booting\Step::__invoke(Neos\Flow\Core\Bootstrap)
13 Neos\Flow\Core\Booting\Sequence::invokeStep(Neos\Flow\Core\Booting\Step, Neos\Flow\Core\Bootstrap)
12 Neos\Flow\Core\Booting\Sequence::invokeStep(Neos\Flow\Core\Booting\Step, Neos\Flow\Core\Bootstrap)
11 Neos\Flow\Core\Booting\Sequence::invokeStep(Neos\Flow\Core\Booting\Step, Neos\Flow\Core\Bootstrap)
10 Neos\Flow\Core\Booting\Sequence::invokeStep(Neos\Flow\Core\Booting\Step, Neos\Flow\Core\Bootstrap)
9 Neos\Flow\Core\Booting\Sequence::invokeStep(Neos\Flow\Core\Booting\Step, Neos\Flow\Core\Bootstrap)
8 Neos\Flow\Core\Booting\Sequence::invokeStep(Neos\Flow\Core\Booting\Step, Neos\Flow\Core\Bootstrap)
7 Neos\Flow\Core\Booting\Sequence::invokeStep(Neos\Flow\Core\Booting\Step, Neos\Flow\Core\Bootstrap)
6 Neos\Flow\Core\Booting\Sequence::invokeStep(Neos\Flow\Core\Booting\Step, Neos\Flow\Core\Bootstrap)
5 Neos\Flow\Core\Booting\Sequence::invoke(Neos\Flow\Core\Bootstrap)
4 Neos\Flow\Cli\CommandRequestHandler::boot("Compiletime")
3 Neos\Flow\Cli\CommandRequestHandler::handleRequest()
2 Neos\Flow\Core\Bootstrap::run()
1 require("/home/circleci/app/Packages/Framework/Neos.Flow/Scripts/flow.php")
```

**Comment by kdambekalns** [comment]
Ok, so I forgot about this PR… By now these commits are in `master` that are related to this:

- [Use PHP 8.0.22-node for CircleCI](https://github.com/neos/neos-ui/commit/caba2e596a720442af1b4d1a86976233d4f1cf97)
- [Update circleci/mariadb:10.2 to cimg/mariadb:10.6](https://github.com/neos/neos-ui/commit/92d9b48888a41e480db2b4fce9303e85007c601d)
- [Use PHP 8.0.22-node for CircleCI unit tests](https://github.com/neos/neos-ui/commit/eef6d9ce083ba6839ba87ed3b0654364ab09ee9a)
- [Allow execution of neos/composer-plugin](https://github.com/neos/neos-ui/commit/dd1f156c4841038234fd31eecc723bf4aeb862a7)
- [Add autoload to dummy TestNodeTypes package](https://github.com/neos/neos-ui/commit/b7c1c4c06e9b275d3871c725c25ff7180ec57c4a)

Sadly the build still fails…

**Comment by kdambekalns** [comment]
@markusguenther Now it looks like a legit test failure, no more PHP issues! 🎉

**Comment by kdambekalns** [comment]
`composer reinstall neos/test-site` seems to solve the configuration issue, at least two content dimensions are configured now for the `2Dimension` fixture.

Now we have yet another error…

**Comment by kdambekalns** [comment]
This looks wrong to me:

```js
if (error[0] && error[0].search('Warning: Unsafe legacy lifecycles') >= 0) {
    delete error[0];
}
if (error[0]) {
    console.log('These console errors were the cause of the failed test:', error);
}
await t.expect(error[0]).notOk();
```

If `error[0]` may not even be set, how can it be safe to use it as an argument later?

**Comment by markusguenther** [comment]
Awesome that you find a way to make it run 🥇 

The ```error[0]``` was a hack in the past because we always got the legacy warnings in the log from React :/

**Comment by kdambekalns** [comment]
Ok, it seems the last failure was… something. Whatever, it passes. Yay! 🎉

**Review by kdambekalns — APPROVED** [review]

**Pull request merged**
