### PR TITLE
BUGFIX: Avoid "stale" nodes when resetting NodeType filter

### PR DESCRIPTION
**Pull request by bwaidelich**
Fixes: #2069

### CODE REVIEW

**Comment by bwaidelich** [comment]
Unfortunately that doesn't do the trick yet..

Here's what I found out and tried before:
We have a mismatch between: "no nodeType filter is active" and "use the default nodeType filter"
That's why we have the `presets.default.baseNodeType` hard coded in several places:

https://github.com/neos/neos-ui/blob/master/packages/neos-ui/src/Sagas/CR/NodeOperations/reloadState.js#L17

https://github.com/neos/neos-ui/blob/master/packages/neos-ui/src/Sagas/UI/PageTree/index.js#L42

I first tried to extend the `SelectBox` component so that you can set a `defaultOption` that is selected when the "reset button" in clicked, but that introduced several issues (i.e. the reset button was not removed, ..).
In general I think it's a good idea to separate the *selected* filter from the *effective* filter but I'm not sure where the best place for that logic would be.

With the current change `matchingNodes` already contains the correct nodes, but it still won't hide the previously filtered ones for some reason

**Comment by dimaip** [comment]
Maybe it happens because you are doing merge? `yield put(actions.CR.Nodes.merge(nodes));`

**Comment by bwaidelich** [comment]
@dimaip Thanks for the input but where do I do a merge and where to change this? And what you wrote is exactly the content of line 151!?

**Comment by dimaip** [comment]
@bwaidelich yes, you merge at line 151. Maybe that is the cause of your troubles, so if you would set the state instead of merging it would work better?
Also, do the nodes that are fetched when filtering have the correct policy information?
Sorry, I'm not deep into how this thing works, but if you need more direct help we could chat on slack or have a hangout some time.

**Comment by bwaidelich** [comment]
> you merge at line 151. Maybe that is the cause of your troubles, so if you would set the state instead of merging it would work better?

Yes. If you mean "we" because I didn't change that part of the code :)
What puzzles me: That exact same code is executed if you select a filter initially and that seems to work (it hides the other nodes).

> Also, do the nodes that are fetched when filtering have the correct policy information?

The only thing I changed is not to break if the filter is reset but set it to the default preset.


Thanks for your input. A quick chat would be great. This should be fairly easy to solve if we look at it together

**Comment by dimaip** [comment]
Sorry for wrong wording, I didn't separate "you" from "we" here, so whatever I refereed to wasn't necessarily caused by any of your changes. Ping me on slack whenever you'd need me.

**Comment by bwaidelich** [comment]
I think that was it: 4e4f39dd179333c828b2bc15a0cfbe78f70f3004

**Comment by bwaidelich** [comment]
We experienced some buggy behavior with the "Refresh" button, but this is unrelated (see #2093). Merging this one now

**Comment by kdambekalns** [comment]
@bwaidelich This could be cherry-picked to 4.0, no?

**Comment by dimaip** [comment]
@kdambekalns sorry, I didn't understand your comment. We only have master branch in this wild wild west corner of Neos development.

**Comment by kdambekalns** [comment]
No worries, my fault. I didn't realise in which corner I was in. :D

**Comment by kdambekalns** [comment]
Still… what about a new release?

**Comment by dimaip** [comment]
Will come when somebody reviews my other open PRs, they are quite important as well :)

**Pull request merged**
