### PR TITLE
BUGFIX: Fix spacing on dimension-switcher dropdown

### LINKED ISSUE #2766: Style issues in the dimension selector
### Description

image

### Steps to Reproduce

Configure content dimensions like described in https://docs.neos.io/cms/manual/content-repository/content-dimensions

#### Actual behavior

- Needs some more space between the dimension labels in the top bar
- Cancel / apply seem to miss some spacing

### Affected Versions

Neos: 5.2

UI: 5.2

### PR DESCRIPTION
**Pull request by c4ll-m3-j4ck**
fixes #2766 

Added some more consistent spacing to the Dimension Switcher in the backend-ui.

Verify by using the forked version and compiling the UI and trying it out in the backend.

Before:
before

After:
before

### CODE REVIEW

**Comment by daniellienert** [comment]
@c4ll-m3-j4ck looks great! Thank you very much!
As it is a bugfix, would you please rebase the PR to version 4.0 (which is equivalent to Neos 4.3) to have it available in all supported versions.

**Comment by c4ll-m3-j4ck** [comment]
I'm not entirely sure how to proceed here, the changes are incompatible with the 4.x branch, the switcher used to be part of a different toolbar entirely. I changed the target branch to 5.3 but I'm not familiar with the way the team manages their branches , so maybe that's wrong in a totally different way. 

Should I try to apply the fixes to the 4.0 branch in another PR?

I'd be grateful for some clarification!

**Comment by daniellienert** [comment]
@c4ll-m3-j4ck,
In general we do bugfixes to the lowest maintained branch. According to https://www.neos.io/features/release-process.html, that would be 4.3. Changes are then upmerged from there to have it available in all versions. 

If code completely changed between 4.3 and master - I'd say,  pick the lowest branch where your changes apply. That probably is 5.0. 
Just changing the target branch only works in very rarer cases. Rebase your branch on 5.0 locally, or if thats not working, branch out from 5.0 again, cherry pick your commit and open a new PR. 

Hope that helps.

**Comment by markusguenther** [comment]
@c4ll-m3-j4ck Hello,

great that you contributed to the UI. I know that @mficzel in Dresden started to move things into the top toolbar.
Need to check to which version this has been merged. If you want I can take care. But in general we check the lowest maintained branch and this is actually 4.0 for the neos 4.3 LTS.

Thanks so far.

**Comment by markusguenther** [comment]
Searched for the change and I was wrong. Martin Moved the preview buttons to the primary toolbar. But found the old PR and it went into neos 5.1.

So we can target neos 5.1 then :)
https://github.com/neos/neos-ui/pull/2462

Do you want to handle that @c4ll-m3-j4ck ?

**Comment by markusguenther** [comment]
Ah saw that the base branch has been changed... 
The trick is to have the commit on the right base branch.

So if you want to change that you can do the following things:
* checkout 5.1 and create a branch from it
* cherry-pick 5004a21
* push the branch as PR and then everything is fine

If you have no mood for that I can do that as well :)

**Review by markusguenther — APPROVED** [review]
Thanks @c4ll-m3-j4ck for fixing that issue. Everything looks fine and I tested this change now with neos 5.1 as we moved the switcher in this version.

Special thanks for the first contribution in the neos-ui. Would be awesome to see more in the future.
🎉 🥇

**Comment by markusguenther** [comment]
Screenshot 2020-09-17 at 22 05 37

Neos 5.1 with the country adjustment.

**Comment by c4ll-m3-j4ck** [comment]
I created #2783, branched off of 5.1 and has 5.1 as the target, I hope that's the right way. So I guess this one can be closed?

**Pull request closed without merging**
