### PR TITLE
BUGFIX: remove underline from links in menu

### PR DESCRIPTION
**Pull request by dimaip**
Fixes: #2039

### CODE REVIEW

**Comment by dimaip** [comment]
@johannessteu AFAIK :visited only affects the color, but color is already overriden to white.

**Comment by mstruebing** [comment]
When I click the burger-icon the blue border it is still visible - tested in chrome

**Comment by dimaip** [comment]
@mstruebing by blue border you mean the :focus outline? We shouldn't just remove it (for keyboard nav), but we can re-style it.

**Comment by dimaip** [comment]
Oh, I looked at the markup and noticed this:
image

So we have a button nested within a link, why?
Maybe it's better to add an option to the Button component to produce <a> links and style them appropriately?

**Comment by dimaip** [comment]
@mstruebing if you don't mind I'll create a separate issue for this and merge this one

**Comment by mstruebing** [comment]
No problem, and keep up your great work! :)

**Pull request merged**
