### PR TITLE
BUGFIX: Fix object traversal in AssetEditor (#1885)

### PR DESCRIPTION
**Pull request by beheist**
See #1885

### CODE REVIEW

**Comment by dimaip** [comment]
But `$get` would not return empty object in case of non-existence, no?

**Comment by mstruebing** [comment]
I've thought it would, but in this case, it's fine like it is.

**Comment by dimaip** [comment]
Looking at this code it should just return `false` https://github.com/grebaldi/plow-js/blob/master/src/projections/atoms/get/index.js#L23

**Comment by beheist** [comment]
So should I change it or leave it? :)

**Pull request merged**
