### PR TITLE
TASK: Add labels to Buttons

### PR DESCRIPTION
**Pull request by mtelgkamp**
- add aria-label to PreviewButton and FullScreenButton

**What I did**
Added aria-label information to buttons
**How to verify it**
Buttons should have an aria-label and screenreader should announce it on focus

Refs: #1592

### CODE REVIEW

**Comment by mstruebing** [comment]
Hey really cool!
I will have a look at it tomorrow. Thank you for your contribution and keep going! ;)

**Comment by mstruebing** [comment]
@dfeyer I think because the checklist is not done yet! :) https://github.com/neos/neos-ui/issues/1592

**Comment by mtelgkamp** [comment]
WIP is because of two reasons:
- The Checklist of #1592 is not done yet
- The labels I introduced are not added to Neos.Neos:Main

I try my best to resolve both asap

**Comment by dimaip** [comment]
Missing labels should not be a problem, as long as you provide a fallback.

**Pull request merged**
