### PR TITLE
FEATURE: dynamic client-side configuration processing

### PR DESCRIPTION
**Pull request by dimaip**
Resolves: #1568

I propose to introduce this API on the same terms as the old API, declaring that it's experimental and may be replaced with a more high-level something. Or if we like it this way, we can just leave it as is and declare support for it later.

---------------------

With React, it's very simple to implement a declarative API, instead of a low-level imperative one like we did before.

I propose to pre-process nodetype definition in the following way: check if the value of a config begins with `ClientEval:` (or any other keyword, can't think of better one right now), if yes then `eval()` it where `node` would be set to the current focused node, with transient values from inspector overlayed on top.

This would allow the following usage:

```
properties:
  serviceType:
    type: string
    ui:
      label: 'Service Type'
      inspector:
        group: product
        editor: 'Content/Inspector/Editors/SelectBoxEditor'
        editorOptions:
          allowEmpty: true
          placeholder: 'Service Type'
          dataSourceIdentifier: 'acme-servicetypes'
  contractType:
    type: string
    ui:
      label: 'Contract Type'
      inspector:
        # only render when serviceType property is set, otherwise move it to an invalid group to hide it
        group: 'ClientEval:node.properties.serviceType ? "product" : "not-rendered"'
        editor: 'Content/Inspector/Editors/SelectBoxEditor'
        editorOptions:
          allowEmpty: true
          placeholder: 'Contract Type'
          dataSourceIdentifier: 'acme-contracttypes'
          dataSourceAdditionalData:
            # use serviceType property as the search term
            searchTerm: 'ClientEval:node.properties.serviceType'
```

A quick demo demonstrating throttling/performance:
peek 2018-02-08 12-04

This config is used in the recording:

```'Neos.NodeTypes.BaseMixins:ImageMixin':
  properties:
    title:
      ui:
        label: 'ClientEval:node.properties.alternativeText'
```

### CODE REVIEW

**Comment by lorenzulrich** [comment]
I must admit I never used this feature in Neos before, but in TYPO3 I used the similar `displayCond` a lot.

I think your proposal will work fine. I think it would be good to inject something more than the `node`, so I could e.g. also check if someone is administrator or to check a property of the parent node - but that might be out of scope.

**Comment by dimaip** [comment]
@lorenzulrich yeah I think such features could potentially be implemented server-side.

**Comment by dimaip** [comment]
I did a lot of experiments with performance. I tried to use immutable data, but it only made things more slow.
The best I got so far is to throttle the TextInput editor. Now it really feels snappy (even better than before), and seems to work fine.

**Comment by dimaip** [comment]
To improve performance I've throttled every editor commit in the EditorEnvelope. Now editing feels a lot snappier than it used to, even without the change.
Processing itself only add 0.3ms to rendering, so it's negligible.

**Comment by kitsunet** [comment]
I like it. Simple but effective! <3 But I feel the prefix is really odd. How about `UiCondition:` or `EvalUi` I feel that's more in line with what we do usually.

**Comment by dimaip** [comment]
@kitsunet thanks, just was too focused on the feature to think about the naming. I like `EvalUi`, as it's really all about evaling any config, and not only conditions.

**Comment by dimaip** [comment]
@kitsunet maybe `ClientEval:`?

**Comment by dimaip** [comment]
@mficzel I've updated an example here, to hide the property by moving it to an invalid group

**Comment by mficzel** [comment]
@dimaip interesting approach for hiding. I like that i will have the option to move a property field away aswell as setting it to readonly. Both makes sense depending on the specific context. 

I like that.

**Comment by dimaip** [comment]
@kdambekalns yes, I just gave a promise to myself that I will not merge it without documentation (and also fix other missing documentation pieces)

**Comment by dimaip** [comment]
Switched to immutableJS. Now full inspector re-eval takes 30ms (instead of 200ms), and as it's throttled, it's not even noticeable.
Will add the docs, polish, fix tests and so on.

**Comment by dimaip** [comment]
OK, I was rather naive.
I throttled the Editors, but forgot to flush the throttle function before things like clicking apply. So it would fire the commit callback already after the component has been unmounted. It's easy to cancel throttled function on unmount, but hard to wait for all children to have fired it before clicking things like apply.
So I gave up on the idea, as it introduces a lot of potential for bugs.
What I did instead is debounce the processing of configuration itself. It's not as fast as fully debounced editor, but at least it doesn't slow things down compared to how they are now.

Will write the docs.

Please review!!!

**Comment by dimaip** [comment]
Docs are ready! /cc @kdambekalns

**Comment by lorenzulrich** [comment]
I went through the documentation which is pretty clear and left some comments regarding spelling.

**Comment by dimaip** [comment]
Anyways, merging, more likely to spot some bugs in master as nobody wants to review.

**Comment by Benjamin-K** [comment]
Have you thought about scenarios where one would like to start a request to an external api or sth? Like you would like to get LatLng of a location you enter into a field for example. Is this possible with the new configuration? 
Anyways, nice work. If the above will also work, even better.

**Comment by mficzel** [comment]
> Have you thought about scenarios where one would like to start a request to an external api or sth? Like you would like to get LatLng of a location you enter into a field for example. Is this possible with the new configuration?

@Benjamin-K i think that would be a use-case for a custom editor implementation.

**Comment by dimaip** [comment]
Yes, exactly, was about to write that. In a custom inspector you may reuse any Editors or UI components, so shouldn't be a lot of extra effort.

**Comment by Benjamin-K** [comment]
Ok, sounds good to me. But custom editors aren't that well documented yet (see http://neos.readthedocs.io/en/stable/ExtendingNeos/CustomEditors.html).

**Comment by dimaip** [comment]
Good point! Could you create an issue? We'll take care.

**Comment by Benjamin-K** [comment]
Issue is here: https://github.com/neos/neos-development-collection/issues/1900

**Comment by skurfuerst** [comment]
Really fancy feature!

**Pull request merged**
