### PR TITLE
TASK: Update plow-js to v3.0.0

### PR DESCRIPTION
**Pull request by grebaldi**
This PR contains an update for `plow-js` v3.0.0 (as tracked here: https://github.com/grebaldi/plow-js/pull/21).

`plow-js` v3.0.0 isn't released yet, that's why currently all packages point to `plow-js` v3.0.0-canary2.

I'd like to use this PR to gather some feedback. I did a smoke test in a limited Neos UI setup, but it would certainly be nice to get some feedback from 1 or 2 real-world projects.

If feedback's positive, I'll do a final release of `plow-js` v3.0.0 and update this PR accordingly.

### CODE REVIEW

**Comment by mhsdesign** [comment]
@markusguenther this got now closed too...

**Comment by Sebobo** [comment]
Yes it now needs to target master, but I cannot change it. 
@grebaldi can you make the change?

**Comment by mhsdesign** [comment]
we need a new pr i guess (i cant even reoopen as the branch is deleted)

**Comment by Sebobo** [comment]
Only the target branch is deleted

**Comment by mhsdesign** [comment]
does need a rebase either way - and probably yarn install with the yarn cache stuff

**Pull request closed without merging**
