### PR TITLE
WIP FEATURE: Update CKEditor5; add Ckeditor inspector debug tool

### PR DESCRIPTION
**Pull request by skurfuerst**
Hey,

I had some time and wanted to get the awesome CKEditor 5 Inspector working in Neos. Was rather easy :)

@dimaip do you have an idea how to handle the breakingness towards people who have written CKeditor plugins?

- [ ] thoroughly test this
- [x] fix unlinking (currently broken)

**!!! Probably this is on the wrong branch; correct?!?!**

All the best,
Sebastian

### CODE REVIEW

**Comment by skurfuerst** [comment]
Screenshot 2019-06-13 at 22 06 18

**Comment by Sebobo** [comment]
Nice! Can at least say that my hyphens plugin works fine, even without recompiling it. 
And also works after recompiling with latest ck version :)
Will check other plugins too.

**Comment by Sebobo** [comment]
Love inspecting my own plugin with the inspector 👍

**Comment by skurfuerst** [comment]
@sebobo in your plugins, do you extend the CKEditor model and use an up/downcaster? If so, I would expect things to break...

All the best,
Sebastian

**Comment by Sebobo** [comment]
I didn't with the last version as it didn't work properly. So I waited for the update to actually use the up/downcasters.

**Comment by skurfuerst** [comment]
Followup PR: https://github.com/neos/neos-ui/pull/2514

**Comment by Sebobo** [comment]
@skurfuerst which is not the follow up? #2514 is this one ;)

**Comment by skurfuerst** [comment]
Ah - #2515 is the followup PR :)

**Pull request closed without merging**
