### PR TITLE
BUGFIX: Prevent closing of the node create dialog

### PR DESCRIPTION
**Pull request by markusguenther**
Adding a random suffix to the checkbox identifier to
prevent to close the node identifier dialog.

The problem is that the BooleanEditor don´t add a random string to the identifier of the checkbox. When you now have the right inspector bar open and the create dialog, you will have two checkboxes with the same identifier. The selectbox in the right inspector wins because this box was rendered first and therefore the dialog gets closed.

You don´t change the checkbox in the dialog, you change the checkbox in the inspector.

Fixes: #2366

### CODE REVIEW

**Comment by markusguenther** [comment]
Thanks to @jonnitto ... your test distribution helped a lot.

**Comment by jonnitto** [comment]
Very nice, thank you!

**Comment by dimaip** [comment]
Ohh that's a nasty bug, good catch!
Is there no way to go without `htmlFor`, e.g. just by wrapping a <label> around?

**Comment by markusguenther** [comment]
The BooleanEditor uses this property but in the end the id will be the same in the dom and therefore it will occur. Or I don’t understand you.

**Comment by dimaip** [comment]
I just mean we could get rid of ids completely.

**Comment by markusguenther** [comment]
Ah so Surround the checkbox by the label and then get rid of the id and for in the rendered markup. Get your point ... will change it later today :)

**Comment by markusguenther** [comment]
@dimaip Adjust that... thanks for the hint. Is much clearer and easier now.

**Pull request merged**
