### PR TITLE
BUGFIX: show translated help message in create new dialog

### LINKED ISSUE #3172: Help message translation is only visible if you click on the question mark
### Description

If you add a `help` message translation with `i18n` to your NodeType, the translation only gets visible if you click on the question mark in your NodeType. But if you hover over the NodeType, you see the full path to your translation.

But if you change the `i18n` in your NodeType to a string, the translation will show up if you hover over your NodeType, and when clicking on the question mark

### Steps to Reproduce

1. Add a help message with a translation to your NodeType:

```yaml
'Vendor.Package:Content.Video':
  ui:
    help:
      message: i18n
```
	
2. Hover over your NodeType, and click the question mark.

3. Change your `message:` to a string:

```yaml
'Vendor.Package:Content.Video':
  ui:
    help:
      message: 'My helpful help message'
```
and hover over your NodeType, and click the question mark.

#### Expected behavior

If you define a help message translation with `i18n` the translations should show up in both cases.

#### Actual behavior

The help message translation doesent show up in both cases.

### Affected Versions

Neos: All

UI: 7.3.6

### PR DESCRIPTION
**Pull request by reflexxion**
Fixes #3172 reported by @crydotsnake

Before:
fix_3172_2
After:
fix_3172_1

### CODE REVIEW

**Review by Sebobo — APPROVED** [review]

**Review by Sebobo — CHANGES_REQUESTED** [review]
Hi @reflexxion 

thx for the fix. Looks good, but this has to go into the 7.3 branch as 5.3 is not supported anymore for bugfixes as per https://www.neos.io/features/release-process.html

**Review by Sebobo — APPROVED** [review]
Thx. The only thing we still might want to check whether the translate method has an issue if its called with `undefined` or `null`

**Comment by reflexxion** [comment]
> Thx. The only thing we still might want to check whether the translate method has an issue if its called with `undefined` or `null`

Ah, my answer was still missing.
No it don't.

**Review by markusguenther — APPROVED** [review]

**Comment by markusguenther** [comment]
Thanks for your very first contribution here 💙

**Pull request merged**
