### PR TITLE
TASK: Update react-collapse to version 4.0.3

### PR DESCRIPTION
**Pull request by markusguenther**
Updating the libray to version 4.0.3.

Resolves: #1920

### CODE REVIEW

**Comment by dimaip** [comment]
Uhm, guys, but did is this issue now resolved with 4.0.3? We didn't upgrade for a reason...
https://github.com/neos/neos-ui/pull/1874

**Comment by markusguenther** [comment]
Hmm I was wondering because I had in mind that I already upgraded this library. Sorry did not see that it was downgraded again.

**Comment by dimaip** [comment]
@markusguenther no need to be sorry, there was no way to know that. I'm just wondering how to prevent somebody else upgrading it in the future (till the problem is solved)... There's no way to leave comments in package.json....

**Comment by JamesAlias** [comment]
Ooops, I did it again 😅

**Pull request merged**
