### PR TITLE
FEATURE: Make default behavior of "Publish"/"Publish all" buttons configurable

### PR DESCRIPTION
**Pull request by danielkestler**
Add a user preference ```publishingModeAll``` (true/false) to configure the publishing behavior, see: https://github.com/neos/neos-ui/issues/107

If set to true, the main publish dropdown button will publish all dirty nodes, if set to false, only the current document node.

Also fixes a bug (?): the auto-publishing settings have not been saved into user preferences until now, this is also fixed.

bildschirmfoto 2018-10-26 um 15 05 22

### CODE REVIEW

**Comment by dimaip** [comment]
I'm still not sure such setting belongs to the UI, and not in Settings.yaml. If the main motivation is to make the publishing process simpler for novice editors, wouldn't presenting them with yet another setting would give them another opportunity to make a mistake?
Anyways, would love to chat with you about this feature, maybe I just miss something.

**Comment by jonnitto** [comment]
I've talked with some of our editors and they would like to see this kind of feature in the UI. Perhaps it would make sense to make a role where I can enable or disable this certain setting for a user.

**Comment by danielkestler** [comment]
Thanks for your feedback, @jonnitto and @dimaip ... I understand both points of view and maybe it would be best to gather some more feedback.

**Comment by danielkestler** [comment]
I have added the "Publish all to" to the main publish dropdown button, if this mode is active. This is a new LL, so we have to make sure it exists in the Neos.Neos package.

**Comment by davidspiola** [comment]
Hi Folks, is this a feature for the 5.1 release?

**Comment by markusguenther** [comment]
@danielkestler It's been a while, do you want to continue the PR or shall we close it down and start again if necessary.

**Comment by danielkestler** [comment]
I think we should close it and start again if this feature is still desired ;)

**Pull request closed without merging**
