### PR TITLE
FEATURE: 4622 - decouple out-of-band rendering from Fusion

### PR DESCRIPTION
**Pull request by nezaniel**
This allows users to use other views than Fusion for out-of-band-rendering

Requires https://github.com/neos/neos-development-collection/pull/4635

### CODE REVIEW

**Review by mficzel — CHANGES_REQUESTED** [review]
Move interface from https://github.com/neos/neos-development-collection/pull/4635 here and extend Neos/Neos/FusionView

**Review by mhsdesign — APPROVED** [review]
Thanks i like this ;)

**Review by ahaeslich — APPROVED** [review]
Tested with the current `Neos.Demo`

**Comment by nezaniel** [comment]
> Move interface from [neos/neos-development-collection#4635](https://github.com/neos/neos-development-collection/pull/4635) here and extend Neos/Neos/FusionView

done

**Review by mficzel — APPROVED** [review]
Fine by 👀

**Pull request merged**
