### PR TITLE
TASK: use ButtonGroup component in InsertModeSelector

### PR DESCRIPTION
**Pull request by dimaip**
I propose to use a button group instead of SelectBox for selecting new element's position.
Why? -- It saves one click, which is quite a lot!

The final styling could be improved with the help of a designer.

What are your thoughts?

New behaviour:

image

### CODE REVIEW

**Comment by dimaip** [comment]
Rebase when this is merged: #478

**Comment by grebaldi** [comment]
I like it, but I think it should go with an explanation, like:

```
Insert mode: [Button] [Button] [Button]
```

**Comment by dimaip** [comment]
@grebaldi agreed, will do it

**Comment by dimaip** [comment]
@grebaldi like this?

image

**Comment by skurfuerst** [comment]
I like!

**Pull request merged**
