### PR TITLE
BUGFIX: Unable to create a Personal Workspace

### PR DESCRIPTION
**Pull request by dfeyer**

### CODE REVIEW

**Comment by dfeyer** [comment]
See my message on Slack https://neos-project.slack.com/archives/C0U0KEGDQ/p1512164595000274

**Comment by dimaip** [comment]
Could somebody with Flow knowledge comment on this?
/cc @kitsunet @grebaldi

**Comment by dfeyer** [comment]
@kitsunet OK, but we need to solve this one before 1.0, right ?

**Comment by dimaip** [comment]
@kitsunet so what about this one?

**Comment by kitsunet** [comment]
Why should the user workspace not be there. It MUST be created while creating a user, if that is not happening that is the bug.

**Comment by kitsunet** [comment]
Do we have a way to reproduce this?

**Comment by dfeyer** [comment]
On my side: 

    flow site:prune && flow site:import Core.Website

And boom ...

**Comment by dfeyer** [comment]
Oh not, I have the same bug, but it's not caused by site:prune / import ... maybe because the setup crash, caused by a broken Sites.xml ... so the CR was not in sane status. 

The problem currently, we don't have any way to get out of this without tweaking the DB.

**Comment by dfeyer** [comment]
in \Neos\Neos\Service\BackendRedirectionService::createWorkspaceAndRootNodeIfNecessary we create the required workspace and node, the question is why this is not used in the current case ?

**Comment by kitsunet** [comment]
Interesting. Maybe we need to have a look at site prune and import. Maybe it removed relevant unser workspace nodes or somthing :/

**Comment by mstruebing** [comment]
Is this PR is still relevant? @dfeyer

**Comment by dfeyer** [comment]
I will close it for now.

**Pull request closed without merging**
