### PR TITLE
BUGFIX: Let selectbox scroll when navigating via keyboard

### LINKED ISSUE #1415: When navigating SelectBox via keyboard up&down keys, it does not scroll
Steps to reproduce:
open references editor, type a few strokes to get a lot of results, move down with arrow down key and wait before you reach the button. Notice that it doesn't scroll.

### PR DESCRIPTION
**Pull request by mstruebing**
closes #1415

### CODE REVIEW

**Comment by mstruebing** [comment]
Could someone test this thing on safari please? :)

**Comment by mstruebing** [comment]
No one?

**Comment by dimaip** [comment]
Sorry, not me.

**Comment by dimaip** [comment]
To hell with it, let's me and wait for bug reports.

**Pull request merged**
