### PR TITLE
TASK: Enable yarn pnp mode

### PR DESCRIPTION
**Pull request by mhsdesign**
use it like this to enable the pnp loader

```sh
yarn node esbuild.js
```

Esbuild version of https://github.com/neos/neos-ui/pull/3192

 
By adding some dependencies to the package.json's i managed to build it successfully via esbuild. Horray!!!

we could add this from https://github.com/react-dnd/react-dnd/issues/1781#issuecomment-584940422
so we can even go pnp strict!!!!

.yarnrc.yml
```yaml
packageExtensions:
  "react-dnd@*":
    dependencies:
      "@react-dnd/invariant": "2.0.0"
```

### CODE REVIEW

**Comment by mhsdesign** [comment]
<details>

The `<NeosContext />` doesnt seem to work from time to time (as the consumer receives null)
and also the react-dnd is broken somehow.

When going to the `<Root />` (Root.js) and removing `<App />` and everything else and just insert "Hello World" the build works at runtime  ;) 

Some screenshots - idk ...

image

image

every stack trace says it originates here:
image

</details>

**Comment by mhsdesign** [comment]
We did it!!!!

image

the problem was, that some dependencies were twice included.
i hacked esbuild a bit to resolve them in the "packages/neos-ui" context -> that way they only appear once in the bundle

this is obviously a hack and should be fixed using yarn ^^ - i have no clue how though :D

```js
onResolve({ filter: /^(react|react-dnd|react-dnd-html5-backend|react-dom|@neos-project\/neos-ui-decorators)$/, namespace: "file" }, ({path, ...options}) =>
    resolve(path, {
        ...options,
        namespace: "noRecurse",
        resolveDir: require('path').join(__dirname, 'packages/neos-ui')
    })
)
```

**Comment by mhsdesign** [comment]
**Edit:** the following errors also appear in the non pnp esbuild -> so its to assume that they will be fixed once they are fixed in #3200 

<details>

okay celebrated a bit too early - drag and drop doesnt work anymore (node tree) and also the ui is sometimes buggy -> "looses" state and shows a blank inspector

This happens when using the selected element box to select a parent node, which is a shortcut

image

Drag and drop:

[Bildschirmaufzeichnung vom 10.10.2022, 10:12:25.webm](https://user-images.githubusercontent.com/85400359/194823489-fdd95b8d-6690-463d-a338-a04c7c46d3b2.webm)

</details>


Fixed :P

**Comment by mhsdesign** [comment]
Is now rebased, but the CI doesnt like it when doing make install ...

```
➤ YN0007: │ @fortawesome/fontawesome-svg-core@npm:1.2.35 must be built because it never has been before or the last one failed
➤ YN0000: │ @fortawesome/fontawesome-svg-core@npm:1.2.35 STDERR (node:1743) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
➤ YN0000: │ @fortawesome/fontawesome-svg-core@npm:1.2.35 STDERR (Use `node --trace-warnings ...` to show where the warning was created)
➤ YN0000: │ @fortawesome/fontawesome-svg-core@npm:1.2.35 STDERR node:internal/errors:477
➤ YN0000: │ @fortawesome/fontawesome-svg-core@npm:1.2.35 STDERR     ErrorCaptureStackTrace(err);
➤ YN0000: │ @fortawesome/fontawesome-svg-core@npm:1.2.35 STDERR     ^
➤ YN0000: │ @fortawesome/fontawesome-svg-core@npm:1.2.35 STDERR 
➤ YN0000: │ @fortawesome/fontawesome-svg-core@npm:1.2.35 STDERR Error [ERR_LOADER_CHAIN_INCOMPLETE]: "file:///home/circleci/project/.pnp.loader.mjs 'resolve'" did not call the next hook in its chain and did not explicitly signal a short circuit. If this is intentional, include `shortCircuit: true` in the hook's return.
➤ YN0000: │ @fortawesome/fontawesome-svg-core@npm:1.2.35 STDERR     at new NodeError (node:internal/errors:387:5)
➤ YN0000: │ @fortawesome/fontawesome-svg-core@npm:1.2.35 STDERR     at ESMLoader.resolve (node:internal/modules/esm/loader:852:13)
➤ YN0000: │ @fortawesome/fontawesome-svg-core@npm:1.2.35 STDERR     at async ESMLoader.getModuleJob (node:internal/modules/esm/loader:431:7)
➤ YN0000: │ @fortawesome/fontawesome-svg-core@npm:1.2.35 STDERR     at async Promise.all (index 0)
➤ YN0000: │ @fortawesome/fontawesome-svg-core@npm:1.2.35 STDERR     at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
➤ YN0000: │ @fortawesome/fontawesome-svg-core@npm:1.2.35 STDERR     at async loadESM (node:internal/process/esm_loader:91:5)
➤ YN0000: │ @fortawesome/fontawesome-svg-core@npm:1.2.35 STDERR     at async handleMainPromise (node:internal/modules/run_main:65:12) {
➤ YN0000: │ @fortawesome/fontawesome-svg-core@npm:1.2.35 STDERR   code: 'ERR_LOADER_CHAIN_INCOMPLETE'
➤ YN0000: │ @fortawesome/fontawesome-svg-core@npm:1.2.35 STDERR }
➤ YN0009: │ @fortawesome/fontawesome-svg-core@npm:1.2.35 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-c0cd5381/build.log)
```

i dont want to say it - but it works on my mashine

**Comment by Sebobo** [comment]
Is this now ready for review?

**Comment by mhsdesign** [comment]
maybe but the tests fail ...

**Comment by Sebobo** [comment]
@mhsdesign I rebased and tried a few more things. I think the problem comes from https://yarnpkg.com/getting-started/migration#upgrade-resolve-to-19 but I tried upgrading resolve everywhere to a compatible version 😔

**Comment by Sebobo** [comment]
ok was an issue with CI and node 16.17 apparently, onward to the next issue!

**Comment by markusguenther** [comment]
Guess we can close this? @mhsdesign

**Comment by mhsdesign** [comment]
Yes - i guess it will take some time until this pnp thing is more stable and automatically works for our case.
With the removal of more than half of our dependencies we already speed up install time.

**Pull request closed without merging**
