### PR TITLE
WIP: Redirecting after node removal

### PR DESCRIPTION
**Pull request by akoenig**
Reference: https://github.com/neos/neos-ui/issues/794

### CODE REVIEW

**Comment by dimaip** [comment]
Hey @akoenig this will be a very nice UX improvement. Do you plan to finish it?

**Comment by akoenig** [comment]
@dimaip Yep, will work on that in the upcoming week.

**Comment by dimaip** [comment]
@akoenig hey, any progress on this? If you want, I can take over.

**Comment by akoenig** [comment]
@dimaip I planned to work on that at the weekend, but I guess in this case you will come up with a solution much quicker due to the fact that you are much deeper in the codebase.

I can give you some remarks I figured before: This server [feedback handler](https://github.com/neos/neos-ui/blob/master/packages/neos-ui/src/manifest.js#L213) gets overwritten by this [one](https://github.com/neos/neos-ui/blob/master/packages/neos-ui-guest-frame/src/manifest.js#L129) and therefore the dispatch of the [focus](https://github.com/neos/neos-ui/blob/master/packages/neos-ui/src/manifest.js#L221) actions does not go through.

**Comment by dimaip** [comment]
@akoenig actually you are absolutely right, it was as simple as you said!
Fixed it here: https://github.com/neos/neos-ui/pull/931

Kind of annoying that you can register only one handler per feedback... Need to do smth about it!

**Pull request closed without merging**
