### PR TITLE
TASK: Change database charset and collation to utf8mb4

### PR DESCRIPTION
**Pull request by kdambekalns**

### CODE REVIEW

**Comment by kdambekalns** [comment]
Huh, probably not really clear but I'd rather have merged all utf8mb4 related changes or none. This one does no harm, though. The tables have their own charset/collation defined anyway. ;)

**Comment by kitsunet** [comment]
An issue with all the PRs could be helpful to keep track and let people know there is more out there :)

**Comment by mstruebing** [comment]
Sorry!

**Comment by kdambekalns** [comment]
> An issue with all the PRs could be helpful

Existed all along… :) https://github.com/neos/flow-development-collection/issues/1268

**Pull request merged**
