### PR TITLE
TASK: Render a separate error when getting 403 status code

### PR DESCRIPTION
**Pull request by daniellienert**

### CODE REVIEW

**Comment by daniellienert** [comment]
Ui-Noob question: I found so many `error()` calls in the code that apparently are rendered as flashmessages without being translated. Is it possible to translate these? How?

**Review by dimaip — APPROVED** [review]

**Comment by dimaip** [comment]
@daniellienert could you please link me to some examples?

**Comment by daniellienert** [comment]
@dimaip -> https://github.com/neos/neos-ui/pull/2795/files#diff-d1ec7f87699ec0c63dc6fafdccefa8bbdb649cb79e713ce049b3ed00a5faca8eR502 😂

**Comment by dimaip** [comment]
Ah!

You could use `i18nRegistry.translate('label')`. The question is how to get the registry there. You might have to pass it along.

**Review by Sebobo — APPROVED** [review]

**Pull request merged**
