### PR TITLE
TASK: Rollback the FEATURE: Skip 'new element' dialog if there is only one

### PR DESCRIPTION
**Pull request by sbruggmann**
The recently introduced Feature https://github.com/neos/neos-ui/pull/2223/files led to irritations on editors side. Let's remove this and someday replace it with other optimizations like: https://github.com/neos/guild-ux/issues/10

### CODE REVIEW

**Comment by rolandschuetz** [comment]
Really? I likes this feature a lot.

Maybe just show some kind of toast "Creating new X node" and show it for 3 seconds, so that it's clearer for users?

**Comment by sbruggmann** [comment]
I think it's better to normalize the behaviour again, without bloating the code base for such a small feature.
It would be better to invest more effort into general optimizations like https://github.com/neos/guild-ux/issues/10

What do you think? @rolandschuetz

**Comment by dimaip** [comment]
Yeah I agree. The same button shouldn't just suddenly change the behavior.

**Comment by rolandschuetz** [comment]
I understand your reasoning. I feel that this small change made working way faster with things like galleries. But both are fine for me.

**Pull request merged**
