### PR TITLE
FEATURE: Add range editor

### PR DESCRIPTION
**Pull request by jonnitto**
Include the range editor from https://github.com/Sebobo/Shel.Neos.RangeEditor

### CODE REVIEW

**Review by markusguenther — APPROVED** [review]
Thanks to @Sebobo for the foundational work and @jonnitto for bringing that to Neos.UI.

**Comment by markusguenther** [comment]
Nice new feature.

**_Suggestion_**

- In a next iteration, usage of Neos constants for the colors (Neos blue for instance)
- When the editor is disabled, also change the blue slider to greyish color
- more space between unit and the input field
- make default value work :)

But that are little tweaks we can achieve in the next step :)

**Comment by markusguenther** [comment]
We need to document this editor as well :)

**Comment by jonnitto** [comment]
Issues are fixed: https://github.com/neos/neos-ui/pull/2998

**Pull request merged**
