### PR TITLE
!!! FEATURE: Upgrade CKEditor 5 from version 16.0.0 to 44.0.0

### LINKED ISSUE #2836: !!! FEATURE: Upgrade CKEditor 5 from version 16.0.0 to 44.0.0
### Description

Currently v16 is in use. As of creating this issue, https://github.com/ckeditor/ckeditor5/releases/tag/v23.1.0 is the latest release.

- [ ] Check breaking changes
- [ ] Decide on target version for neos-ui
- [ ] Update
- [ ] Test extensibility

### PR DESCRIPTION
**Pull request by skurfuerst**
This update represents a major leap forward, spanning several years of development. Due to the extensive changes and numerous breaking changes, it’s challenging to provide a comprehensive list of all API alterations. As such, this PR introduces a **breaking change**.

The CKEditor API has evolved significantly, and any plugins relying on outdated APIs may no longer function as expected. We cannot provide a detailed upgrade guide for your custom or third-party plugins. Instead, we recommend consulting the release notes of CKEditor 5 for the relevant versions. Note that during testing, some packages dependent on the old implementation were found incompatible.

To support the community, we aim to review a few community plugins and, where feasible, submit PRs to update them, offering practical examples.

This upgrade effort has been attempted multiple times over the years, but often proved too challenging to complete. We want to acknowledge and thank those who contributed to earlier PRs addressing this task, including @JamesAlias, @73nici, @skurfuerst , @mhsdesign , and @markusguenther 

**Testing Notes**:
Acceptance tests for editable content elements encountered issues with the new CKEditor. The workaround implemented in this PR leverages TestCafe’s proposed solution, but it only works reliably in Chrome. Fortunately, the TestCafe team has already merged a PR that will likely resolve this issue in the future.

Special thanks to everyone involved in this significant effort!

Please see https://discuss.neos.io/t/feedback-needed-in-which-release-to-include-ckeditor-5-update/6707 for context and discussion.

Resolves: https://github.com/neos/neos-ui/issues/2836

### CODE REVIEW

**Comment by markusguenther** [comment]
As described in the commits, the new type around buttons are not implemented in the UI yet. The buttons create a paragraph before or after the table. At the moment, we hide the buttons as we miss the styles and the functionality.

TBH, as we can just use ENTER to add a paragraph, I am unsure if we need it.
Screenshot 2024-12-02 at 21 37 17

With the latest commits, I also fixed the table drop-downs. We try to render an image with an SVG as markup in the src attribute. As this does not work and the fallback label was not aligned horizontally. Now we transform the svg to an data-uri and use this.
Screenshot 2024-12-02 at 21 37 02

**Comment by markusguenther** [comment]
Will try to check the tests tomorrow. A hint can be maybe that issue https://github.com/DevExpress/testcafe/issues/7642

**Comment by markusguenther** [comment]
Although I added some workarounds I still have some failing tests in the Syncing Test suites.
I hope that I can resolve them somehow. The patch of testcafe did not work for me.

Hope that they the community finds a solution for the contentEditable issue in testcafe.
https://github.com/DevExpress/testcafe/issues/8321

**Comment by mhsdesign** [comment]
when i click on a shortcut this pops up in the bottom (and the publish toolbar is gone):

image

**Comment by mhsdesign** [comment]
And i think we should put special focus on these things when testing:

- our place holders (that they look like before)
  - for spans
  - for block elments
  - for autoparagraph things true or false
  - centered elements 
  - -> remove this patch https://github.com/neos/neos-ui/pull/3864 (and possibly other outdated ckeditor hacks / patches?)
- bundle size and other features
  - for example ckeditor comes with some kind of finder: https://ckeditor.com/docs/ckeditor5/44.0.0/features/file-management/ckfinder.html but we need that and also not other things.

**Comment by markusguenther** [comment]
For auto-paragraphs we have a test ;)
The placeholders work fine, and I could not reproduce the CKEditor bar from your image.

But I am open for feedback :)
Lucky that the tests are green again with some tweaks for the CKEditor, but hope that testcafe version 3.7.1 comes with a fix. A change has been merged today that promises to solve that 🤞

**Comment by markusguenther** [comment]
Found a bug with the table toolbar. When you edit a table and go to another page, the toolbar is empty except the table dropdowns. But the bugs seem familiar to me, so will check if it is just an old one.

**Comment by markusguenther** [comment]
> Found a bug with the table toolbar. When you edit a table and go to another page, the toolbar is empty except the table dropdowns. But the bugs seem familiar to me, so will check if it is just an old one.

🙈 Found the matching issue for that https://github.com/neos/neos-ui/issues/3512

**Comment by mhsdesign** [comment]
THANK you so much for your effort!

> and I could not reproduce the CKEditor bar from your image.

now its already less big and without branding - i assume because of the licence key thingy?

but still after clicking randomly on document nodes below the `appContainer` there will be elments which take a couple pixels in height and push the ui upwards:

image

the code looks like

```
<div class="ck ck-clipboard-drop-target-line ck-hidden"></div>
<div class="ck ck-aria-live-announcer"><div aria-live="polite" aria-relevant="additions"><ul class="ck ck-aria-live-region-list"></ul></div><div aria-live="assertive" aria-relevant="additions"><ul class="ck ck-aria-live-region-list"></ul></div></div>
```

so i think we need to disable some kind of drag and drop plugin and also this aria-live thing? https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_arialiveannouncer-AriaLiveAnnouncer.html

(tested on firefox and safari)

**Comment by markusguenther** [comment]
Thanks, @mhsdesign ... I will take a look. Maybe my screen is too small. Used just the MacBook for the week.

**Comment by markusguenther** [comment]
Tested the CKEditor in Drupal and TYPO3 and the powered by is rendered in both OSS CMS.
So maybe we should put into the toolbar or so.

**TYPO3 v13**
Screenshot 2024-12-13 at 11 06 13

**Drupal 10**
Screenshot 2024-12-13 at 11 13 12

**Comment by markusguenther** [comment]
We (Neos 9 weekly meeting) decided to merge this, and if we have issues and/or future adjustments that are needed to be done as a follow-up.

**Comment by jonnitto** [comment]
Thank you all for your efforts and work. Awesome! ❤️

**Pull request merged**
