### PR TITLE
TASK: Update to testcafe 19.2.0

### PR DESCRIPTION
**Pull request by markusguenther**
Updates testcafe to the lastest version 19.1.0 with lots of bugfixes and some new features like screen shots. Also updates the testcafe-react-selectors.

Resolves: #1733

### CODE REVIEW

**Comment by dimaip** [comment]
I suspect you also need to update their react selectors library...

**Comment by dimaip** [comment]
Ah, sorry, you actually do update it...

**Comment by markusguenther** [comment]
@dimaip Yeah first updated to the latest 1.1.0 but that did not work out and the 1.0.6 is already linked to testcafe 19.1.0. Need to investigate this. Because it turns out that the new versions should fix the testcafe issue #2015 but I now have the problem that this pops up in the  version. https://github.com/DevExpress/testcafe/issues/2015

Already comment the issue and hopefully they can help ... but will investigate this soonish ;)

**Comment by markusguenther** [comment]
The testcafe fix is already approved but is waiting for merge and release. When the version gets released I will upgrade the package and hopefully then everything is working in the right way :)

**Pull request merged**
