### PR TITLE
TASK: Indicate a no matches found in nodetypes select

### PR DESCRIPTION
**Pull request by johannessteu**

### CODE REVIEW

**Comment by dimaip** [comment]
Maybe add some icon to the text, e.g. https://fontawesome.com/icons/ban?style=solid or other?
Maybe even gray out the text?
@danielkestler wdyt?

**Comment by danielkestler** [comment]
This dialog is more complex than it seems at first sight. Will also have a look at it ;-)

**Comment by johannessteu** [comment]
Anything i can do here?

**Comment by dimaip** [comment]
@danielkestler do you still plan to do something about this one, or should we merge it for now?

**Comment by danielkestler** [comment]
@dimaip Sorry, been a bit busy in the last weeks. Will have a look tomorrow!

**Comment by danielkestler** [comment]
Bildschirmfoto 2019-04-16 um 07 43 53

**Comment by dimaip** [comment]
@danielkestler I'm not sure about the choice of the icon. This exclamation mark usually means a warning or an error of some sort, but here it's just an empty result set. What do you think about this one? https://fontawesome.com/icons/ban?style=solid

**Comment by dimaip** [comment]
Better yet would be empty-set icon, but it's pro-only: https://fontawesome.com/icons/empty-set?style=regular

**Comment by danielkestler** [comment]
@dimap The ban-icon is also fine for me, shall we change?

**Comment by dimaip** [comment]
@danielkestler I'd certainly prefer it, if there are no better suggestions.

**Comment by danielkestler** [comment]
@dimaip I like it 🙂

Bildschirmfoto 2019-04-17 um 10 15 37

**Comment by johannessteu** [comment]
Anyone up to merge it?

**Pull request merged**
