### PR TITLE
BUGFIX: Allow for rendering of secondary editors in NodeCreationDialog

### LINKED ISSUE #1034: Integrate the editors also in the creating dialog
At the moment, not all available editors (e.g. DateTime) are available in the creationDialog. In order to make advanced use of https://github.com/Flowpack/Flowpack.NodeTemplates/, it is important to have all of them in the dialog.

### PR DESCRIPTION
**Pull request by grebaldi**
Hi there,

this PR is an attempt to finally allow secondary editors (like the media selection screen or the image cropper) to be used in the NodeCreationDialog.

The result looks like this:

https://user-images.githubusercontent.com/2522299/104287035-2a932700-54b6-11eb-9ce2-45f8724339f6.mp4

_**EDIT**: Updated video to better reflect the latest style changes._

## What has been done?

- SaveHook-Logic was extracted from the inspector saga and put into "Changes" scope, so it could be shared between inspector and node creation dialog
- General overhaul of NodeCreationDialog to achieve support for SaveHooks and SecondaryInspector
- Additional "jumbo" style for Dialog component was added
- An `ImagePropertyNodeCreationHandler` was added to the Integration Test distribution to decouple this change from an additional change that needs to be done in Neos.Neos in order to support `showInCreationDialog`

## Addional Notes

- Some of the e2e-Tests cover some of the NodeCreationDialog already. A more thorough Test suite would probably exceed the scope of this PR, so I'll leave it at that. If, however, anyone discovers problems with the NodeCreationDialog during manual testing, I'm going to add an e2e-Test for that specific scenario in this PR.
- In order for this change to really make sense, the following PR for `Neos.Neos` needs to be merged as well: https://github.com/neos/neos-development-collection/pull/3270
  - That change re-enables all editors for the NodeCreationDialog

fixes  #1034

### CODE REVIEW

**Comment by jonnitto** [comment]
Very nice!

**Comment by daniellienert** [comment]
Cannot judge the code, but I really like the feature!

**Comment by markusguenther** [comment]
Thanks for the great PR. Right now I am bit busy and hope to review it soonish 🙏

**Review by dimaip — APPROVED** [review]
Wow, amazing change! Seems to work and the code looks good!

**Comment by mficzel** [comment]
@markusguenther any opinion on this? Would be great to get this in.

**Comment by Sebobo** [comment]
Works even mostly with the new Media UI selection, nice <3 

Bildschirmfoto 2021-01-28 um 15 40 52

Just needs a bit more love with styling on my side and a detection whether the editor is shown in the creation dialog.
Is this already available?

**Comment by Sebobo** [comment]
So I looked through the code and I don't understand all of it, but looks fine in general. Also could not find problems with functionality so far.

So I assume I could check for `ui.nodeCreationDialog.isOpen` to adjust the layout of my secondary inspector.

**Review by Sebobo — APPROVED** [review]

**Comment by mficzel** [comment]
@markusguenther can we merge this?

**Comment by markusguenther** [comment]
Thanks to all folks involved ❤️

**Pull request merged**
