### PR TITLE
FEATURE: Responsive grid UI

### LINKED ISSUE #3149: Collapsible Document tree to make room for the Content tree
Jira issue originally created by user @aertmann:

STUB: The Document tree should be collapsible in order to make more room for the Content tree in cases of pages with lots of content

 Jira-URL: https://jira.neos.io/browse/NEOS-781

### PR DESCRIPTION
**Pull request by Sebobo**
**What I did**

Made the Neos UI more responsive and flexible. This also brings the following features and benefits:

- [x] Resizeable left sidebar
- [x] Resizeable document tree
- [x] Most positioning code could be removed
- [x] Restructured markup a bit and cleanup up related CSS

**How I did it**

Instead of having every ui layout component having absolute sizes and positions the base layout is now a CSS grid and each component has an area assigned. This way the whole layout can be controlled from the wrapping container.

**How to verify it**

* Open the Neos UI and resize the left sidebar & document tree with the little resize icons in the bottom right. 
* Try fullscreen mode 
* Toggle the sidebars

Resolves: #3149

### CODE REVIEW

**Comment by mhsdesign** [comment]
Nice ^^ thanks!

some related infos:

i guess this problem now intensifies: https://github.com/neos/neos-ui/issues/2691


about https://github.com/neos/neos-ui/issues/3149
as you said:
> [...] the structure is a bit strange. The two trees are not proper siblings in the sidebar. When this is cleaned up it should also be easy to adjust their relative heights

**Comment by mhsdesign** [comment]
fyi here is the slack thread (with video) https://neos-project.slack.com/archives/C0U0KEGDQ/p1665750470219249

**Comment by mhsdesign** [comment]
Hi ;) i got around trying this out

https://user-images.githubusercontent.com/85400359/197408922-b4836864-5a30-4bc0-b138-922049f8f04b.mp4

if found some issues:
- there is now a white spot next to the discard button
- one cannot foldout the content tree via dragging when its collapsed
  - solution A: change the react collapse to state to "open" somehow?
  - solution B: hide this css option via js, if collapsed
- when trying to collapse the content tree too much another scrollbar is shown 
  - solution A: change the react collapse state to "close"  somehow
  - solution B: set a min-height which cannot be undercut when dragging (maybe max-height too ^^)
- one can only start the drag in these exact corners
   - i guess this is a css limitation? 

collapsing the sidebars, full-screen and secondary inspector is working fine (well without animation for now ...) ;)

https://user-images.githubusercontent.com/85400359/197408954-841292c4-3cd2-413c-bad3-61cf54f1e70c.mp4

**Comment by Sebobo** [comment]
This Chrome 107 news could help us with getting in animations again https://web.dev/css-animated-grid-layouts/

**Comment by Sebobo** [comment]
@mhsdesign thx for the review, I fixed the 3 points you mentioned.
The CSS resize feature is a bit limited. We might replace it later with some JS feature, but until we know what we want I prefer the native functionality. I'll check if we can style it somehow.

**Comment by Sebobo** [comment]
Here is also an example how to resize with JS as its apparently now possible to style the icon https://stackoverflow.com/questions/35702705/is-there-a-way-to-change-the-css-resize-corners-position

**Comment by mhsdesign** [comment]
Thanks for fixing these things ;)

- [x] there is now a white spot next to the discard button
- [x] one cannot foldout the content tree via dragging when its collapsed (via: B: hide this css option via js, if collapsed)
- [x] (partially see below) when trying to collapse the content tree too much another scrollbar is shown

---------

Hmm its not so well shown on video - but when the content tree is folded out the moving of the document tree is a bit laggier than when the content tree is hidden. The content tree itself is also quite smooth.

https://user-images.githubusercontent.com/85400359/198038812-9b14bb09-bd15-4988-9ca3-96a389e423ee.mp4


----------

One can fold the content tree to 0 height - but the js collapsed state is not changed. (Proposal: add a min-height or something)
Actually this is not a real problem :D

https://user-images.githubusercontent.com/85400359/198039231-41908a31-abc4-4350-bef3-8e82b9c02779.mp4


----------


> i guess this problem now intensifies: https://github.com/neos/neos-ui/issues/2691

;D

lets talk about a strategy to fix #2691 once and for all

maybe make it scrollable or break into two lines?

if i remember correctly the html structure up there is horrible :D

https://user-images.githubusercontent.com/85400359/198040129-4fb413a9-dc15-40b7-b565-c7340ff7880b.mp4

**Comment by Sebobo** [comment]
> Hmm its not so well shown on video - but when the content tree is folded out the moving of the document tree is a bit laggier than when the content tree is hidden. The content tree itself is also quite smooth.

No clue why, would need to check the browser performance tool

> One can fold the content tree to 0 height - but the js collapsed state is not changed. (Proposal: add a min-height or something) Actually this is not a real problem :D

There is already a min-height of `40px` which we could increase. I already though about setting it to ~ 120px to include the toolbar and the document node.

> lets talk about a strategy to fix #2691 once and for all
> 
> maybe make it scrollable or break into two lines?

Scroll often doesn't work properly with various input devices.
I'll try breaking 🔨

**Comment by markusguenther** [comment]
Will check the pipeline, and we need a new version of `@neos-project/eslint-config-neos` for the code style

**Comment by markusguenther** [comment]
Hmm not sure if I now break it but I can not resize the left side bar 🤷‍♂️
But the rest of the Backend looks nice :)

**Review by markusguenther — APPROVED** [review]
Awesome feature... thanks for that. 
Tested locally on Firefox, Chrome and Safari 💙

**Pull request merged**
