### PR TITLE
TASK: Update eslint-config-neos

### PR DESCRIPTION
**Pull request by mstruebing**
Let's see if travis likes these changes too

### CODE REVIEW

**Comment by mstruebing** [comment]
Seems not, tldr: it's a dependency hell.

Seems like a package doesn't use eslint > 4.9

https://github.com/eslint/eslint/issues/9486

**Comment by markusguenther** [comment]
@mstruebing The last time I updated this we need to adjust the neos/eslint-config-neos and also the packages in the neos-ui... because all are using eslint as well.

I will take a look soonish. Because I am not able to release a new version of neos/eslint-config-neos  I needed to start there ;)

**Comment by mstruebing** [comment]
I already released a new version for your latest fixes -  and it's possible to clone the repo inside `node_modules`, right?

**Comment by dimaip** [comment]
I had to update eslint in other PR, seems to work, so I think this can be closed. Please reopen if I'm wrong.

**Pull request closed without merging**
