### PR TITLE
BUGFIX: Property group configured as collapsed must be collapsed

### PR DESCRIPTION
**Pull request by lorenzulrich**

### CODE REVIEW

**Comment by lorenzulrich** [comment]
I don't understand why the frontend test fails. The test failing only has to do with collapsing the right side as a whole.

**Comment by mstruebing** [comment]
Locally the tests are failing too. When I inspect the RightSideBar I see that the Property isHidden is behaving correctly.
When I remove the last asserting and click it is running through.
As soon as I add it is failing.

**Comment by mstruebing** [comment]
maybe @dimaip can help here? :)

**Comment by dimaip** [comment]
Will try to dig into it over the weekend.

**Comment by mstruebing** [comment]
I rebased on latest master, see if this helps.

**Comment by mstruebing** [comment]
Seems an old testcafe version was the problem or something.

**Pull request merged**
