### PR TITLE
TASK: Use new after login routing and set routes for new backend

### PR DESCRIPTION
**Pull request by kitsunet**
This re-configures the routes for use as default backend and overwrites
the default route after login to go to the new UI.

Fixes: #1290
Depends: https://github.com/neos/neos-development-collection/pull/1794

### CODE REVIEW

**Comment by dimaip** [comment]
So how do you enable the old UI?

**Comment by kitsunet** [comment]
@dimaip You overwrite the route settings back to what you see in the Neos change in your global settings for example.

**Comment by kitsunet** [comment]
Sounds cumbersome, but then we all said this should be the exceptoin for special projects. And it opens up a lot of flexibility about this in the future.

**Comment by dimaip** [comment]
@kitsunet but if you override the routes, will it be possible to use both UIs at the same time? How would the switching work then?

**Comment by kitsunet** [comment]
I thought we don't support switching back and forth. I also don't think that's a good idea. But generally both seem to work if you call the respective URLs. The configuration "just" defines the entry point after login.

**Comment by dimaip** [comment]
But that was the very point that @skurfuerst brought up, that we need to support switching back and forth for the transitional period.
Otherwise one could just remove the UI package, that would have the same effect...

So with the adjusted Routes, the behavior would be like this:
`/neos!` = new UI
`/neos` = old UI
Correct?
Will the login still work correctly?

**Comment by kitsunet** [comment]
for the above I would have to adjust a few things again. I didn't understand that switching back and forth is a requirement and IMHO that is really a bad idea.

**Comment by dimaip** [comment]
But that's clearly described as a requirement in @skurfuerst write up.
I personally am not opinionated on this, but I see why Sebastian asks for it.
As said, if you want the switch to be permanent then why bother, just remove the UI package and the old UI would start working, no?

**Comment by kitsunet** [comment]
ok, 👎 from me for now. I need to figure something out that I missed. So we NEED the session value to determine which is the active UI. you cannot simply switch UIs and have the other UI. Just because the metadata rendering is not compatible, so the rendering must know which backend is the active one.

That means I need to provide an actual mechanism to switch around. AKA add a controller + route(s) that allows you to switch around which is the currently active UI and then redirect to that all the time. I have an idea but I couldn't wrap my head around implementing it tonight anymore.

**Comment by dimaip** [comment]
Couldn't we just use the system that we already have in place (that redirect aspect)?

**Comment by kitsunet** [comment]
Basically yes, but I don't see the need for an aspect. Will brew up something...

**Comment by skurfuerst** [comment]
Hey everybody :)

@kitsunet I'd be up for discussing it tomorrow or so if you like :-)

All the best, Sebastian

**Comment by kitsunet** [comment]
Ok, here we go. This should make every scenario possible in some way or the other.

a) new UI not installed, obviously works, nothing special here.
b) new UI installed with default settings -> All routes (eg /neos) will lead you to the new UI. You can switch to the old by using the switch in user menu. The "Content" entry in the module menu will always bring you back to the new UI though (which probably makes sense as it is default now)

c) new UI installed, overwrote the default route back to old UI like this:

```
Neos:
  Neos:
    userInterface:
      # The below configuration sets this to the "old" UI route.
      routeAfterLogin:
        values:
          '@package': 'Neos.Neos'
          '@controller': 'Frontend\Node'
          '@action': 'show'
          '@format': 'html'
```

Now you are in the trickiest state.  The route /neos and subsequent login will get you to the old UI. The "content" module entry will get you to the old UI. As we have no user interface element to switch now, you have two options `/neos!` will get you to the new UI as well as `neos/content` but you need to know that. We can obviously think about adding some UI element to the old UI but that is not part of this change then.

**Comment by mficzel** [comment]
@kitsunet the solution seems fine to me. If i understand it correctly it should be possible to create a third-party-package that adds the route-settings plus the back and forth switch via unplanned extensibility. So imho no need to have that in the core.

**Comment by kitsunet** [comment]
Only thing open I just noticed in discussion if we want to allow to remove the "go to old UI" button for cases if you fully switched to new UI.

**Comment by dimaip** [comment]
Go to old UI should just be removed. This scenario of co-existence of UIs is still kind of marginal, so I don't think we should invest into it too much.

**Comment by kitsunet** [comment]
Also fine. Maybe do that in a separate change then? Otherwise we can obviously do it here too if needed.

**Comment by dimaip** [comment]
Separate change. @skurfuerst can we merge this?

**Comment by skurfuerst** [comment]
Looks awesome <3

**Comment by skurfuerst** [comment]
I'd keep the button to swithc to the old UI... for now... but that's something to be discussed

**Pull request merged**
