### PR TITLE
BUGFIX: Let unapplied changes overlay cover everything except inspector

### LINKED ISSUE #2670: Editor is not warned about unsave changes in inspector (on publish, on page close)
### Description

One of the editors of our customer stumbled upon the following issue:

### Steps to Reproduce

1. Do changes in the content area - now you have unpublished changes
2. Open the inspector on the right and change something there, but "forget" to click the apply button
3. You are used to the system warning you about unsaved changes in the inspector
4. You click the publish button and get the feedback, that all was successfully published
5. The change in the inspector is still unsaved, but you do not notice it, because in former versions of Neos you got a warning, if you left the inspector without hitting the "apply" button.
6. You log our or close the window and your change is lost without you even realizing it.

#### Expected behavior

If you click on the top frame when there is an not-applied change in the inspector, you should get the same warning about unsaved changes as when you click in the content area.

### Affected Versions

Neos: 5.x
UI: 5.x

This is not a big issue, but might be fixed easily and would avoid frustration for the editors.

### LINKED ISSUE #3174: Escape "Unapplied changes" when using "Selected element" to navigate to other Node
### Description
Funnely it works astonishing well and is not buggy at all ^^ - i just found an escape hatch.

### Steps to Reproduce

1. Make changes on a Content Element (in the Inspector)
2. use the Selected element selectbox to move upward (Content Collection / Page)

#### Expected behavior

Idk - but for some reason its not allowed to change the node by using the Content Tree with unapplied changes - so i assumed the same for the "Selected element"  select box.

#### Actual behavior

You moved to the other node ^^ 
now you are free ;)  - unless you go back to the edited node.

### Affected Versions

UI version: v8.0.1

### PR DESCRIPTION
**Pull request by grebaldi**
fixes: #2670

**The problem**

The unapplied changes overlay is supposed to prevent all editing actions as long as there are pending changes in the inspector, so that the user is forced to make a decision of whether to apply or discard their changes and prevent them from accidentally losing their unsaved work.

Unfortunately, the unapplied changes overlay does not cover the entire user interface, but only the content canvas area:

Screenshot_2023-05-12_12-35-38 - 2670 before

This (unintentionally) allows the user to perform all kinds of actions (like changing the edit-/preview-mode, discarding changes, etc.) and potentially lose their progress.

**The solution**

The first part of the solution is the attempt to let the unapplied changes overlay cover the entire user interface (minus the inspector area):
Screenshot_2023-05-12_13-43-29 - 2670 after

This is done in three steps:

1. Move the overlay directly underneath the document body via `ReactDOM.createPortal`, so that it competes for z-index globally
2. Adjust the positioning of the `&::after`-element, so it covers the entire top bar
3. Set the `--zIndex-Dialog` variable to a value that allows only flash messages to be drawn on top of the overlay

Step 3 turned out to be a bit tricky, because of the logic manifested in `packages/build-essentials/src/styles/styleConstants.js`. I was unable to achieve the desired effect without changing the variables name from `--zIndex-UnappliedChangesOverlay-Context` to `--zIndex-UnappliedChangesOverlay`, which is possibly breaky to anyone who relies on the former (this isn't official API though and is very unlikely to have any noticable effect).

I also adjusted `--zIndex-UnappliedChangesOverlay` in `cssVariables.css`, expecting that this will be necessary for later versions.

The second part of the solution has to do with the unapplied changes *dialog*. After I've tested the overlay, I noticed that the semi-transparent dialog overlay also did not cover the entire user interface:

Screenshot_2023-05-12_13-20-43 - 2670 zIndex Problem

I had noticed this before and documented the faulty behavior in #2925. To make the unapplied changes mechanism work as intended, I decided to fix this z-index issue in the scope of this PR as well.

Similar to the unapplied changes overlay, I had to rename `--zIndex-Dialog-Context` to `--zIndex-Dialog`.

*P.s.: The blurs you've undoubtedly noticed in the screenshots are being addressed over here: https://github.com/neos/neos-ui/pull/3489*

**EDIT:** E2E-tests revealed that I needed to adjust the z-index configuration for select box dropdowns as well. Hooray for E2E-tests! :smile:

### CODE REVIEW

**Comment by mhsdesign** [comment]
> I also adjusted --zIndex-UnappliedChangesOverlay in cssVariables.css, expecting that this will be necessary for later versions.

1000% wow thanks, Yes this is due to dropping the `styleConstants.js` in the future (8.3) https://github.com/neos/neos-ui/pull/3366

and here is my description, as to why we have them also in the 7.3 branch ^^ https://github.com/neos/neos-ui/pull/3438

**Review by crydotsnake — APPROVED** [review]
Tested and works as expected!

**Review by mhsdesign — CHANGES_REQUESTED** [review]
Thanks ;) works as described (tested on 8.3 to make sure the new cssVariables work)

what do you think about making the overlay also cover the "select element" box as well as the publishing dropdown:

image

this would then also resolve: https://github.com/neos/neos-ui/pull/3501

currently one can publish changes and also escape to the workspaces backend module via the selector.


another little detail i noticed on 8.3, is that the mouse becomes a pointer and the hover effect is triggered for the language select box
image

the language selectbox will also open, their items not be selectable:

image


probably an z-index issue

**Comment by grebaldi** [comment]
@mhsdesign:
> what do you think about making the overlay also cover the "select element" box as well as the publishing dropdown:

Good point. I'd find that quite sensible (also think that `<SelectedElement/>` has actually no structural point in being part of the Inspector in the first place tbh.). It'd be also less risky compared to #3501.

If I get a couple of :+1: on this plan, I'll change it here and close #3501 :D

**Comment by mhsdesign** [comment]
Yes I believe it’s much easier to maintain than to have #3501 in our code base. Sorry that you went through the hassle of creating #3501 if we discard your work

**Comment by grebaldi** [comment]
Done :)

@mhsdesign:
> Yes I believe it’s much easier to maintain than to have https://github.com/neos/neos-ui/pull/3501 in our code base. Sorry that you went through the hassle of creating https://github.com/neos/neos-ui/pull/3501 if we discard your work

No worries! I'm all for it: Less entropy, fewer troubles :)

**Review by crydotsnake — COMMENTED** [review]
It works as expected!

I remembered one more tiny detail. If you follow the steps in the issue to reproduce this bug, even though the inspector is dimmed, it is still possible for me to publish my changes even though I still have changes in the inspector that I haven't saved.


SCR-20230612-osed

Would it be a big effort to disable the publish button in such a case? Or should we discuss that maybe for Neos 9? Does it even make sense? 😅

**Comment by grebaldi** [comment]
@crydotsnake:
> I remembered one more tiny detail. If you follow the steps in the issue to reproduce this bug, even though the inspector is dimmed, it is still possible for me to publish my changes even though I still have changes in the inspector that I haven't saved.

I can't reproduce that... In my setup, the publish button lights up orange, but if I click it, I get the "Unapplied Changes"-dialog as expected.

But then again I think it makes sense to give more visual indication here... I'll see what I can do :)

**Comment by mhsdesign** [comment]
@grebaldi thank you so much for your adjustments.

I think its fine to not show any additional visual indication in the publish button, and either way it could be done in a separate pr (if at all ^^)

I will try this out and see if it as expected overlays with the publish button and then id say this is ready to be merged!

@crydotsnake are you sure that you can still click the publish button? Could you please try to debug this if so, maybe by checking with other browsers and investigating the css styles in the dev tools.

**Comment by mhsdesign** [comment]
https://github.com/neos/neos-ui/assets/85400359/17cc6f5c-da7c-4ad3-83a3-cef0f409027a

@crydotsnake _it works on my mashine_ (well i cheated again as i tested it cherry-cheryy-lady picked on 8.3 :P

**Review by mhsdesign — APPROVED** [review]
Thanks it works now perfectly ;) And should survive the upmerge ^^

**Review by crydotsnake — APPROVED** [review]
Tested it again, and its working great!

**Comment by grebaldi** [comment]
I've just noticed a regression :(

The "Unapplied changes" overlay now covers the secondary inspector. This makes it impossible to crop images. I will come up with a fix soon.

**Comment by mhsdesign** [comment]
> The "Unapplied changes" overlay now covers the secondary inspector. This makes it impossible to crop images. I will come up with a fix soon.


oh well good catch 😅 i was about to release it the next days - we def need e2e test for that??? Should have affected every secondary inspector right? - I forgot to test that as well ^^

**Pull request merged**
