### PR TITLE
TASK: Update react-close-on-escape

### PR DESCRIPTION
**Pull request by mstruebing**

### CODE REVIEW

**Comment by markusguenther** [comment]
Do we really need this dependency? We use it only in the dialog component and the package just checks if I press escape.

Couldn't we just implement this single method in the dialog component and get rid of the dependency?
Don't blame it, just asking?

**Comment by dimaip** [comment]
Fine with me, makes total sense in spirit of the recent backlash against small packages :)

**Comment by mstruebing** [comment]
Yep would absolutely agree on that.

**Comment by markusguenther** [comment]
Should I adjust that on master or on typescript branch? Or do in in master and then adjust it for typescript branch? Don't know the time schedule for the typescript merge.

**Comment by mstruebing** [comment]
I would say first do it on master, adjusting this for typescript shouldn't be that hard (maybe I'm wrong with this assumption^^)

**Comment by markusguenther** [comment]
Did remove the package now with these PR https://github.com/neos/neos-ui/pull/2274

**Pull request closed without merging**
