### PR TITLE
FEATURE: Add file upload and asset selection in asset list editor

### PR DESCRIPTION
**Pull request by gerhard-boden**
This adds asset selection and file upload to the asset list editor.

It's also possible to just drag files onto the asset list.

#resolves: #1304 #1306

### CODE REVIEW

**Comment by gerhard-boden** [comment]
had no idea we had that, how "newly" is "newly"? When creating this I did similar like the ``ImageEditor`` handles uploads

**Comment by kitsunet** [comment]
Which uses that upload component :)

https://github.com/neos/neos-ui/blob/master/packages/neos-ui-editors/src/Editors/Image/Components/PreviewScreen/index.js#L41

**Comment by gerhard-boden** [comment]
Ah, haha 😄 Now that I see it, I remember it... I think I could also wrap the whole Asset List with that ``AssetUpload`` (like I currently do with the ``Dropzone``). Not sure why I did not do that in the first place, no hard reasons I hope.

**Comment by kitsunet** [comment]
I think this can be change afterwards too.

**Comment by dimaip** [comment]
Awesome! But would be nice to finish it the nice way before the release. @gerhard-boden Will you take care of it or should we just create a reminder ticket?

**Comment by gerhard-boden** [comment]
@dimaip I'll take care of it, I just created a "reminder ticket" for myself
https://github.com/neos/neos-ui/issues/1329
Hopefully will do it tomorrow or even today. SHOULD not make a lot of trouble

**Comment by dimaip** [comment]
@gerhard-boden no hurry now that we have it in, just wanted to make sure it doesn't get left behind. Thanks for taking care!

**Comment by gerhard-boden** [comment]
The reason why I did not use ``AssetUpload`` in the first place was that it had no support for multiple files. This is also changed in https://github.com/neos/neos-ui/pull/1378 alongside with the proposed change for ``AssetList``

**Pull request merged**
