### PR TITLE
TASK: Use new editorconfig-checker

### PR DESCRIPTION
**Pull request by mstruebing**
This uses the "new" editorconfig-checker with some more features :)

### CODE REVIEW

**Comment by dimaip** [comment]
Anything we can do about the tests?

**Comment by mstruebing** [comment]
I don't think the failing e2e tests have anything to do with my PR and need to be fixed in master.

**Comment by dimaip** [comment]
Could you please rebase? For some reason I can not push into your branch...

**Comment by mstruebing** [comment]
Thanks for repairing the tests :)

**Comment by dimaip** [comment]
Hah it wasn't just the tests, we actually had to fix Neos master itself. Kinda cool that our tests now help to catch Neos Bugs as well :)

**Pull request merged**
