### PR TITLE
BUGFIX: Build extensiblity plugins without class transform

### PR DESCRIPTION
**Pull request by Sebobo**
Relates: #3287

**What I did**

**How I did it**

**How to verify it**

Build the Neos extensibility examples

### CODE REVIEW

**Comment by Sebobo** [comment]
@markusguenther we also need to downgrade babel from 7 to 6 as its a dependency of build-essentials.

**Comment by grebaldi** [comment]
Sorry, I didn't mean to intervene here :sweat_smile: 

But since I've been fiddling around with Visol.Neos.LinkClass and was able to verify that this branch + babel downgrade fixed the issue I've encountered there, I took the liberty of pushing my changes.

Please feel free to handle my changes as you see fit :)

**Comment by markusguenther** [comment]
BTW: Tested that change with the extensibility examples, and it worked nice after the test release with 8.2.1-beta1 I figured out that the build had the issue with typescript. The reason was that the dist folder is not used.

So, I now adjust the module path while the release.
More in the PR https://github.com/neos/neos-ui/pull/3314

But with that, it works perfect and the people just need to add ```"@neos-project/build-essentials": "version-number",``` to the own plugin.

**Comment by markusguenther** [comment]
**Can be tested:**

The packages just need to change the dependencies like that.
```
"@neos-project/neos-ui-extensibility": "8.2.1-beta2",
"@neos-project/build-essentials": "8.2.1-beta2"
```

**Comment by grebaldi** [comment]
Hi @markusguenther,

thanks a lot for those beta releases!

I was able to successfully test them with `Visol.Neos.LinkClass`.

**Pull request merged**
