### PR TITLE
FEATURE: Add blockquote to selectable styles

### PR DESCRIPTION
**Pull request by Sebobo**
**What I did**

Made blockquote available as text style

**How I did it**

Added the necessary config to the toolbar and CK config

**How to verify it**

CK Blockquote

### CODE REVIEW

**Comment by crydotsnake** [comment]
Do i need to enable this in my NodeType first? I understood it to mean that it is now selectable by default. Or do I understand something wrong?

**Comment by ahaeslich** [comment]
> Do i need to enable this in my NodeType first? I understood it to mean that it is now selectable by default. Or do I understand something wrong?

With this change the possibility to activate blockquote as editor option is added. You still need to enable it in your NodeTypes like it was done in `Tests/IntegrationTests/SharedNodeTypesPackage/NodeTypes/Document/Page.yaml`.

Per default no special formatting options are set for inline editable text.

**Comment by crydotsnake** [comment]
> 



> > Do i need to enable this in my NodeType first? I understood it to mean that it is now selectable by default. Or do I understand something wrong?
> 
> With this change the possibility to activate blockquote as editor option is added. You still need to enable it in your NodeTypes like it was done in `Tests/IntegrationTests/SharedNodeTypesPackage/NodeTypes/Document/Page.yaml`.
> 
> Per default no special formatting options are set for inline editable text.

Thanks for explanation! was just a bit confused 🙂

**Review by crydotsnake — APPROVED** [review]
Tested and its working as expected!

**Comment by Sebobo** [comment]
Sorry for not mentioning it. I will have to separately enable it in the `Neos.NodeTypes.BaseMixins` for the `TextMixin` in a separate PR. I had adjusted it but then forgot that it's a different repo.
But I have to check the e2e test. I think the dropdown is now higher and the test misbehaves. Or maybe I will just deactivate it for the test again...

**Review by jonnitto — APPROVED** [review]

**Review by markusguenther — APPROVED** [review]
Thanks for that feature. Works like expected 👍

**Comment by crydotsnake** [comment]
Related PR for enabling the blockquote formating by default in the text mixin: https://github.com/neos/neos-development-collection/pull/4027

**Pull request merged**
