### PR TITLE
BUGFIX: Adjust ContentElementWrapping aspect to recent changes

### PR DESCRIPTION
**Pull request by bwaidelich**
This adjusts the `AugmentationAspect` so that it respects the
`additionalAttributes` argument introduced with https://github.com/neos/neos-development-collection/pull/1919

Resolves: #1647

### CODE REVIEW

**Comment by skurfuerst** [comment]
I have a slight preference currently to *not* making this a public API; in fact IMHO the CEWrappingService should *only* add things needed for technical reasons to the Neos UI.

However, I also do not have a clear idea how to realize what you want. For all Content Elements inheriting from Neos.Fusion:Tag, it is obviously easy; but for everything inheriting Template and Content, it is obviously more difficult.

What about making the Content Element Wrapping Service (and the fusion object) more configurable to make it possible to add additional attributes via Fusion? Then everybody relying on these kinds of styles can add them explicitely in the Fusion objects; but we do not make this a public "magic" API.

What do you think @bwaidelich and @lorenzulrich ? :-)

All the best,
Sebastian

**Comment by bwaidelich** [comment]
I like the idea to make the ContentElementWrapping extensible! I'll try to implement this as a follow-up commit

**Comment by bwaidelich** [comment]
This requires https://github.com/neos/neos-development-collection/pull/1919 to be merged!

**Comment by bwaidelich** [comment]
Since neos/neos-development-collection#1919 is merged in the meantime, can we merge this one, @skurfuerst ?  (I merged current master and successfully tested it)

**Comment by bwaidelich** [comment]
I consider this a no-brainer and the failing tests are most probably not related. So I decided to merge this myself for lack of reviews. I take full responsibility ;)

**Comment by mstruebing** [comment]
It seems the tests are related to your PR - the e2e tests are currently broken in master

**Comment by bwaidelich** [comment]
@mstruebing But how can that be related?

**Comment by bwaidelich** [comment]
It was indeed related 🙈 #1773 fixes the CI

**Pull request merged**
