### PR TITLE
BUGFIX:  Orange change indicator should be aligned left

### PR DESCRIPTION
**Pull request by skurfuerst**
Fixes: #911

### CODE REVIEW

**Comment by dimaip** [comment]
image
1.

**Comment by crazydrecksack** [comment]
@dimaip: I am on this

**Comment by crazydrecksack** [comment]
oct-05-2017 13-47-18

additonally increased click area for collapse icon and fixed offset of spinner

**Comment by dimaip** [comment]
Thanks for taking care, looks good to me!

**Pull request merged**
